/**
 * @file filter_test.c
 * @brief Tests for algo/filter — selective copy matching a predicate
 *
 * Three API levels tested:
 *   Level 1 — Generic (algo_filter): void* interface, any element type
 *   Level 2 — Typed macro (ALGO_FILTER_TYPED): compile-time sizeof
 *   Level 3 — Typed slice (algo_filter_slice_int / algo_filter_slice_Point)
 *
 * Two instantiations:
 *   int   — primary; all three levels exercised
 *   Point — struct coverage; slice level only
 *
 * Covers:
 *   - algo_filter()             — basic copy of matching elements
 *   - ALGO_FILTER_TYPED()       — same semantics, automatic sizeof
 *   - algo_filter_slice_int()   — typed slice variant
 *   - algo_filter_slice_Point() — struct coverage
 *   - Empty input (len=0)       — returns 0, output untouched
 *   - out_cap == 0              — returns 0, no writes
 *   - All match                 — all elements copied, count == len
 *   - None match                — returns 0, output untouched
 *   - Mixed                     — partial match, order preserved
 *   - Truncation                — return == out_cap, more matches exist
 *   - Exact fit                 — return == out_cap, no truncation
 *   - Context parameter         — pred uses ctx to parameterize threshold
 *   - Stability                 — relative order of matching elements preserved
 *   - Pred call count           — stops calling pred after out_cap matches
 *   - Single element            — matching and non-matching
 *
 * Fuzz entry point (CANON_FUZZING):
 *   - Filters a u8 array for elements above a fixed threshold
 *   - Reference model: independent linear scan of full input
 *   - Invariants checked after every call:
 *       • return value <= out_cap
 *       • return value == reference count (buffer is always large enough)
 *       • every output element satisfies pred
 *       • output order matches order of matching elements in input
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/primitives/compare.h"
#include "core/slice.h"
#include "algo/filter/filter.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice instantiations ──────────────────────────────────────────── */

DEFINE_SLICE(int)
DEFINE_ALGO_FILTER(int)

typedef struct { int x; int y; } Point;
DEFINE_SLICE(Point)
DEFINE_ALGO_FILTER(Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void filter_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ════════════════════════════════════════════════════════════════════════════
   Unit test build
   ════════════════════════════════════════════════════════════════════════════ */

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Predicate helpers ───────────────────────────────────────────────────── */

static bool pred_positive(const void* elem, void* ctx)
{
    (void)ctx;
    return *(const int*)elem > 0;
}

static bool pred_negative(const void* elem, void* ctx)
{
    (void)ctx;
    return *(const int*)elem < 0;
}

static bool pred_even(const void* elem, void* ctx)
{
    (void)ctx;
    return (*(const int*)elem % 2) == 0;
}

static bool pred_gt_threshold(const void* elem, void* ctx)
{
    return *(const int*)elem > *(const int*)ctx;
}

static bool pred_always_true(const void* elem, void* ctx)
{
    (void)elem; (void)ctx;
    return true;
}

static bool pred_always_false(const void* elem, void* ctx)
{
    (void)elem; (void)ctx;
    return false;
}

/* Counting predicate — tracks how many times it was called */
static int g_call_count = 0;
static bool pred_positive_counting(const void* elem, void* ctx)
{
    (void)ctx;
    g_call_count++;
    return *(const int*)elem > 0;
}

/* Point predicate: x > y */
static bool pred_point_x_gt_y(const void* elem, void* ctx)
{
    (void)ctx;
    const Point* p = (const Point*)elem;
    return p->x > p->y;
}

/* ── test_empty_input ────────────────────────────────────────────────────── */
static void test_empty_input(void)
{
    int out[4] = {99, 99, 99, 99};

    /* Generic: len=0 → 0 written, out untouched */
    int dummy[1] = {1};
    usize n = algo_filter(dummy, 0, sizeof(int), pred_positive, NULL, out, 4);
    EXPECT(n == 0);
    EXPECT(out[0] == 99); /* untouched */

    /* Typed macro */
    n = ALGO_FILTER_TYPED(out, 4, dummy, 0, int, pred_positive, NULL);
    EXPECT(n == 0);

    /* Typed slice: empty slice */
    slice_int empty = slice_int_empty();
    n = algo_filter_slice_int(empty, out, 4, pred_positive, NULL);
    EXPECT(n == 0);
    EXPECT(out[0] == 99); /* still untouched */
}

/* ── test_zero_cap ───────────────────────────────────────────────────────── */
static void test_zero_cap(void)
{
    int in[]  = {1, 2, 3};
    int out[4] = {99, 99, 99, 99};

    /* out_cap=0 → immediate return, no writes */
    usize n = algo_filter(in, 3, sizeof(int), pred_positive, NULL, out, 0);
    EXPECT(n == 0);
    EXPECT(out[0] == 99);

    /* Typed macro */
    n = ALGO_FILTER_TYPED(out, 0, in, 3, int, pred_positive, NULL);
    EXPECT(n == 0);

    /* Typed slice */
    slice_int sv = slice_int_from(in, 3);
    n = algo_filter_slice_int(sv, out, 0, pred_positive, NULL);
    EXPECT(n == 0);
    EXPECT(out[0] == 99);
}

/* ── test_all_match ──────────────────────────────────────────────────────── */
static void test_all_match(void)
{
    int in[]  = {1, 2, 3, 4, 5};
    int out[5] = {0};

    usize n = algo_filter(in, 5, sizeof(int), pred_positive, NULL, out, 5);
    EXPECT(n == 5);
    EXPECT(out[0] == 1 && out[1] == 2 && out[2] == 3 &&
           out[3] == 4 && out[4] == 5);

    /* Typed macro */
    int out2[5] = {0};
    n = ALGO_FILTER_TYPED(out2, 5, in, 5, int, pred_positive, NULL);
    EXPECT(n == 5);
    EXPECT(out2[4] == 5);

    /* Typed slice */
    int out3[5] = {0};
    slice_int sv = slice_int_from(in, 5);
    n = algo_filter_slice_int(sv, out3, 5, pred_positive, NULL);
    EXPECT(n == 5);
    EXPECT(out3[0] == 1 && out3[4] == 5);
}

/* ── test_none_match ─────────────────────────────────────────────────────── */
static void test_none_match(void)
{
    int in[]   = {1, 2, 3, 4, 5};
    int out[5] = {99, 99, 99, 99, 99};

    /* Looking for negatives — none exist */
    usize n = algo_filter(in, 5, sizeof(int), pred_negative, NULL, out, 5);
    EXPECT(n == 0);
    EXPECT(out[0] == 99); /* untouched */

    /* Typed slice */
    int out2[5] = {99, 99, 99, 99, 99};
    slice_int sv = slice_int_from(in, 5);
    n = algo_filter_slice_int(sv, out2, 5, pred_negative, NULL);
    EXPECT(n == 0);
    EXPECT(out2[0] == 99);
}

/* ── test_mixed ──────────────────────────────────────────────────────────── */
static void test_mixed(void)
{
    int in[]  = {-1, 2, -3, 4, 0, 5};
    int out[6] = {0};

    /* Filter positives: {2, 4, 5} */
    usize n = algo_filter(in, 6, sizeof(int), pred_positive, NULL, out, 6);
    EXPECT(n == 3);
    EXPECT(out[0] == 2 && out[1] == 4 && out[2] == 5);

    /* Filter negatives: {-1, -3} */
    int out2[6] = {0};
    n = algo_filter(in, 6, sizeof(int), pred_negative, NULL, out2, 6);
    EXPECT(n == 2);
    EXPECT(out2[0] == -1 && out2[1] == -3);

    /* Filter even: {2, 4, 0} */
    int out3[6] = {0};
    n = algo_filter(in, 6, sizeof(int), pred_even, NULL, out3, 6);
    EXPECT(n == 3);
    EXPECT(out3[0] == 2 && out3[1] == 4 && out3[2] == 0);

    /* Typed slice */
    int out4[6] = {0};
    slice_int sv = slice_int_from(in, 6);
    n = algo_filter_slice_int(sv, out4, 6, pred_positive, NULL);
    EXPECT(n == 3);
    EXPECT(out4[0] == 2 && out4[1] == 4 && out4[2] == 5);
}

/* ── test_truncation ─────────────────────────────────────────────────────── */
static void test_truncation(void)
{
    /* 5 positives in input, but out_cap=2 — truncated */
    int in[]  = {1, 2, 3, 4, 5};
    int out[2] = {0};

    usize n = algo_filter(in, 5, sizeof(int), pred_positive, NULL, out, 2);
    EXPECT(n == 2);          /* return == out_cap signals possible truncation */
    EXPECT(out[0] == 1);     /* first match */
    EXPECT(out[1] == 2);     /* second match — stopped here */

    /* Typed slice: same expectation */
    int out2[3] = {0};
    slice_int sv = slice_int_from(in, 5);
    n = algo_filter_slice_int(sv, out2, 3, pred_positive, NULL);
    EXPECT(n == 3);
    EXPECT(out2[0] == 1 && out2[1] == 2 && out2[2] == 3);

    /* Mixed input: {-1, 2, -3, 4, -5, 6} — positives are {2, 4, 6}
     * With out_cap=2: get {2, 4}, truncated (6 not written) */
    int mixed[] = {-1, 2, -3, 4, -5, 6};
    int out3[2] = {0};
    n = algo_filter(mixed, 6, sizeof(int), pred_positive, NULL, out3, 2);
    EXPECT(n == 2);
    EXPECT(out3[0] == 2 && out3[1] == 4);
}

/* ── test_exact_fit ──────────────────────────────────────────────────────── */
static void test_exact_fit(void)
{
    /* Exactly 3 positives, out_cap=3 — return==out_cap but NOT truncated */
    int in[]  = {1, -1, 2, -2, 3};
    int out[3] = {0};

    usize n = algo_filter(in, 5, sizeof(int), pred_positive, NULL, out, 3);
    EXPECT(n == 3);
    EXPECT(out[0] == 1 && out[1] == 2 && out[2] == 3);
    /* return == out_cap here, but all matching elements fit — caller must
     * re-run with larger buffer or domain knowledge to confirm no truncation */
}

/* ── test_context_parameter ──────────────────────────────────────────────── */
static void test_context_parameter(void)
{
    int in[]  = {1, 5, 3, 8, 2, 10};
    int out[6] = {0};

    /* Keep elements > 4 */
    int threshold = 4;
    usize n = algo_filter(in, 6, sizeof(int), pred_gt_threshold, &threshold, out, 6);
    EXPECT(n == 3);
    EXPECT(out[0] == 5 && out[1] == 8 && out[2] == 10);

    /* Keep elements > 7 */
    threshold = 7;
    int out2[6] = {0};
    n = algo_filter(in, 6, sizeof(int), pred_gt_threshold, &threshold, out2, 6);
    EXPECT(n == 2);
    EXPECT(out2[0] == 8 && out2[1] == 10);

    /* Keep elements > 100 — none */
    threshold = 100;
    int out3[6] = {99};
    n = algo_filter(in, 6, sizeof(int), pred_gt_threshold, &threshold, out3, 6);
    EXPECT(n == 0);
}

/* ── test_stability ──────────────────────────────────────────────────────── */
static void test_stability(void)
{
    /* Matching elements must appear in the same relative order as in input */
    int in[]  = {3, -1, 1, -4, 2, -7, 5};
    int out[7] = {0};

    usize n = algo_filter(in, 7, sizeof(int), pred_positive, NULL, out, 7);
    EXPECT(n == 4);
    EXPECT(out[0] == 3); /* first positive in input */
    EXPECT(out[1] == 1); /* second */
    EXPECT(out[2] == 2); /* third */
    EXPECT(out[3] == 5); /* fourth */

    /* Stability with evens: {3,-1,1,-4,2,-7,5} → evens are {-4, 2} */
    int out2[7] = {0};
    n = algo_filter(in, 7, sizeof(int), pred_even, NULL, out2, 7);
    EXPECT(n == 2);
    EXPECT(out2[0] == -4 && out2[1] == 2);
}

/* ── test_pred_call_count ────────────────────────────────────────────────── */
static void test_pred_call_count(void)
{
    /* Input: {1, 2, 3, 4, 5} — all positive.
     * With out_cap=3: pred called 3 times (fills output), then stops. */
    int in[]  = {1, 2, 3, 4, 5};
    int out[3] = {0};

    g_call_count = 0;
    usize n = algo_filter(in, 5, sizeof(int), pred_positive_counting, NULL, out, 3);
    EXPECT(n == 3);
    EXPECT(g_call_count == 3); /* stopped after writing 3rd match */

    /* No matches: pred called for all 5 elements */
    int in2[]  = {-1, -2, -3, -4, -5};
    int out2[5] = {0};
    g_call_count = 0;
    n = algo_filter(in2, 5, sizeof(int), pred_positive_counting, NULL, out2, 5);
    EXPECT(n == 0);
    EXPECT(g_call_count == 5); /* checked all — none matched */

    /* out_cap=0: pred never called */
    g_call_count = 0;
    n = algo_filter(in, 5, sizeof(int), pred_positive_counting, NULL, out, 0);
    EXPECT(n == 0);
    EXPECT(g_call_count == 0);
}

/* ── test_single_element ─────────────────────────────────────────────────── */
static void test_single_element(void)
{
    int pos[1] = {7};
    int neg[1] = {-3};
    int out[1] = {0};

    EXPECT(algo_filter(pos, 1, sizeof(int), pred_positive, NULL, out, 1) == 1);
    EXPECT(out[0] == 7);

    out[0] = 0;
    EXPECT(algo_filter(neg, 1, sizeof(int), pred_positive, NULL, out, 1) == 0);
    EXPECT(out[0] == 0); /* untouched */
}

/* ── test_typed_macro ────────────────────────────────────────────────────── */
static void test_typed_macro(void)
{
    int in[]  = {-2, 0, 3, -1, 6, -4, 9};
    int out[7] = {0};

    /* ALGO_FILTER_TYPED deduces sizeof(int) correctly */
    usize n = ALGO_FILTER_TYPED(out, 7, in, 7, int, pred_positive, NULL);
    EXPECT(n == 3);
    EXPECT(out[0] == 3 && out[1] == 6 && out[2] == 9);

    /* Truncation via typed macro */
    int out2[1] = {0};
    n = ALGO_FILTER_TYPED(out2, 1, in, 7, int, pred_positive, NULL);
    EXPECT(n == 1);
    EXPECT(out2[0] == 3); /* first match only */

    /* Empty via typed macro */
    n = ALGO_FILTER_TYPED(out, 7, in, 0, int, pred_positive, NULL);
    EXPECT(n == 0);
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    Point in[] = {{5, 1}, {2, 3}, {7, 4}, {1, 8}, {6, 6}};
    Point out[5];
    memset(out, 0, sizeof(out));

    /* Keep points where x > y: {5,1}, {7,4} */
    slice_Point sv = slice_Point_from(in, 5);
    usize n = algo_filter_slice_Point(sv, out, 5, pred_point_x_gt_y, NULL);
    EXPECT(n == 2);
    EXPECT(out[0].x == 5 && out[0].y == 1);
    EXPECT(out[1].x == 7 && out[1].y == 4);

    /* None match */
    Point in2[] = {{1, 5}, {2, 3}, {0, 1}};
    Point out2[3];
    memset(out2, 0, sizeof(out2));
    slice_Point sv2 = slice_Point_from(in2, 3);
    n = algo_filter_slice_Point(sv2, out2, 3, pred_point_x_gt_y, NULL);
    EXPECT(n == 0);

    /* Empty slice */
    slice_Point empty = slice_Point_empty();
    n = algo_filter_slice_Point(empty, out, 5, pred_point_x_gt_y, NULL);
    EXPECT(n == 0);
}

/* ── test_always_predicates ──────────────────────────────────────────────── */
static void test_always_predicates(void)
{
    int in[]  = {1, 2, 3, 4, 5};
    int out[5] = {0};

    /* pred_always_true: all elements copied */
    usize n = algo_filter(in, 5, sizeof(int), pred_always_true, NULL, out, 5);
    EXPECT(n == 5);
    EXPECT(out[0] == 1 && out[4] == 5);

    /* pred_always_false: nothing copied */
    int out2[5] = {99, 99, 99, 99, 99};
    n = algo_filter(in, 5, sizeof(int), pred_always_false, NULL, out2, 5);
    EXPECT(n == 0);
    EXPECT(out2[0] == 99);
}

/* ── Suppress unused ─────────────────────────────────────────────────────── */
static void filter_suppress_unused(void)
{
    (void)algo_filter_slice_Point;
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)filter_suppress_unused;
    (void)filter_slice_suppress_unused;

    test_empty_input();
    test_zero_cap();
    test_all_match();
    test_none_match();
    test_mixed();
    test_truncation();
    test_exact_fit();
    test_context_parameter();
    test_stability();
    test_pred_call_count();
    test_single_element();
    test_typed_macro();
    test_point_struct();
    test_always_predicates();

    if (g_failed == 0) {
        printf("OK  filter_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  filter_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void filter_fuzz_suppress_unused(void)
{
    (void)algo_filter_slice_int;
    (void)algo_filter_slice_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz algo_filter on a raw byte array.
 *
 * Predicate: keep bytes where value > 127 (high-byte filter).
 *
 * Invariants verified after every call:
 *   1. return value <= out_cap
 *   2. return value == reference count (buffer is always large enough)
 *   3. every element in out satisfies pred
 *   4. order of out matches order of matching elements in input
 */

static bool pred_high_byte(const void* elem, void* ctx)
{
    (void)ctx;
    return *(const u8*)elem > 127;
}

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)filter_fuzz_suppress_unused;
    (void)filter_slice_suppress_unused;

    if (size == 0) return 0;

    /* Output buffer — always large enough to hold all matching elements */
    u8 out[256];
    usize out_cap = sizeof(out);

    usize n = algo_filter(data, size, sizeof(u8), pred_high_byte, NULL,
                          out, out_cap);

    /* Invariant 1: return value <= out_cap */
    if (n > out_cap) __builtin_trap();

    /* Build reference independently */
    u8 ref[256];
    usize ref_count = 0;
    for (usize i = 0; i < size; i++) {
        if (data[i] > 127) ref[ref_count++] = data[i];
    }

    /* Invariant 2: count matches reference */
    if (n != ref_count) __builtin_trap();

    /* Invariant 3: all output elements satisfy pred */
    for (usize i = 0; i < n; i++) {
        if (out[i] <= 127) __builtin_trap();
    }

    /* Invariant 4: output order matches reference order */
    for (usize i = 0; i < n; i++) {
        if (out[i] != ref[i]) __builtin_trap();
    }

    return 0;
}

#endif /* CANON_FUZZING */
