/**
 * @file find_test.c
 * @brief Tests for algo/find — locate first element matching a predicate
 *
 * Three API levels tested:
 *   Level 1 — Generic (algo_find): void* interface, bool return, optional outputs
 *   Level 2 — Typed macro (ALGO_FIND_TYPED): compile-time sizeof, typed out pointer
 *   Level 3 — Typed slice:
 *       algo_find_slice_int        → option_int  (Some on match, None otherwise)
 *       algo_find_index_slice_int  → usize       (CANON_USIZE_MAX if not found)
 *
 * Two instantiations:
 *   int   — primary; all three levels exercised
 *   Point — struct coverage; slice level only
 *
 * Covers:
 *   - algo_find()                   — basic search
 *   - ALGO_FIND_TYPED()             — same semantics, automatic sizeof
 *   - algo_find_slice_int()         — returns option_int
 *   - algo_find_index_slice_int()   — returns usize index
 *   - algo_find_slice_Point()
 *   - algo_find_index_slice_Point()
 *   - Empty sequence (len=0)        — returns false / None / CANON_USIZE_MAX
 *   - Not found                     — returns false, outputs NOT written
 *   - Match at first element        — index 0
 *   - Match at last element         — index n-1
 *   - Match in middle               — correct index returned
 *   - First match wins              — multiple matches, only first returned
 *   - NULL output parameters        — both out_index and out_elem may be NULL
 *   - Output not written on miss    — output vars unchanged when pred never matches
 *   - Context parameter             — pred uses ctx to parameterize
 *   - Short-circuit                 — pred not called after first match
 *   - option_int_is_some / unwrap   — option semantics verified
 *   - CANON_USIZE_MAX sentinel      — verified on no-match
 *
 * Fuzz entry point (CANON_FUZZING):
 *   - Finds first byte > 127 in a raw byte array
 *   - Reference model: independent linear scan
 *   - Invariants:
 *       • found ↔ reference found
 *       • if found: index matches reference index
 *       • if found: element satisfies pred
 *       • if found: no element before index satisfies pred
 *       • if not found: no element in array satisfies pred
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/primitives/limits.h"
#include "core/primitives/compare.h"
#include "core/slice.h"
#include "semantics/option/option.h"
#include "algo/find/find.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice + option instantiations ─────────────────────────────────── */

DEFINE_SLICE(int)
CANON_OPTION(int)
DEFINE_ALGO_FIND(int)

typedef struct { int x; int y; } Point;
DEFINE_SLICE(Point)
CANON_OPTION(Point)
DEFINE_ALGO_FIND(Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void find_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ════════════════════════════════════════════════════════════════════════════
   Unit test build
   ════════════════════════════════════════════════════════════════════════════ */

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Suppress unused option functions generated by CANON_OPTION ──────────── */
static void find_option_suppress_unused(void)
{
    /* int option — only is_some and unwrap are used in tests */
    (void)option_int_is_none;
    (void)option_int_get;
    (void)option_int_unwrap_or;
    (void)option_int_expect;
    (void)option_int_map;
    (void)option_int_and_then;
    (void)option_int_or_else;
    (void)option_int_filter;
    (void)option_int_combine_with;
    (void)option_int_replace;
    (void)option_int_take;
    (void)option_int_eq;

    /* Point option — only is_some and unwrap are used in tests */
    (void)option_Point_is_none;
    (void)option_Point_get;
    (void)option_Point_unwrap_or;
    (void)option_Point_expect;
    (void)option_Point_map;
    (void)option_Point_and_then;
    (void)option_Point_or_else;
    (void)option_Point_filter;
    (void)option_Point_combine_with;
    (void)option_Point_replace;
    (void)option_Point_take;
    (void)option_Point_eq;
}

/* ── Predicate helpers ───────────────────────────────────────────────────── */

static bool pred_negative(const void* elem, void* ctx)
{
    (void)ctx;
    return *(const int*)elem < 0;
}

static bool pred_gt_threshold(const void* elem, void* ctx)
{
    return *(const int*)elem > *(const int*)ctx;
}

static bool pred_always_false(const void* elem, void* ctx)
{
    (void)elem; (void)ctx;
    return false;
}

static bool pred_eq_value(const void* elem, void* ctx)
{
    return *(const int*)elem == *(const int*)ctx;
}

/* Short-circuit counter */
static int g_call_count = 0;
static bool pred_negative_counting(const void* elem, void* ctx)
{
    (void)ctx;
    g_call_count++;
    return *(const int*)elem < 0;
}

/* Point predicate: x == y */
static bool pred_point_eq(const void* elem, void* ctx)
{
    (void)ctx;
    const Point* p = (const Point*)elem;
    return p->x == p->y;
}

/* ── test_empty_sequence ─────────────────────────────────────────────────── */
static void test_empty_sequence(void)
{
    int dummy[1] = {42};
    usize idx = 99;
    const void* ep = (const void*)0x1;

    /* Generic: len=0 → false, outputs untouched */
    bool found = algo_find(dummy, 0, sizeof(int), pred_negative, NULL, &idx, &ep);
    EXPECT(!found);
    EXPECT(idx == 99);           /* not written */
    EXPECT(ep == (const void*)0x1); /* not written */

    /* Typed macro */
    const int* p = (const int*)0x1;
    found = ALGO_FIND_TYPED(dummy, 0, int, pred_negative, NULL, &idx, &p);
    EXPECT(!found);

    /* Typed slice: empty */
    slice_int empty = slice_int_empty();
    option_int opt = algo_find_slice_int(empty, pred_negative, NULL);
    EXPECT(!option_int_is_some(opt));

    usize i = algo_find_index_slice_int(empty, pred_negative, NULL);
    EXPECT(i == CANON_USIZE_MAX);
}

/* ── test_not_found ──────────────────────────────────────────────────────── */
static void test_not_found(void)
{
    int arr[] = {1, 2, 3, 4, 5};
    usize idx = 99;
    const int* ep = (const int*)0x1;

    /* Looking for negatives — none exist */
    bool found = algo_find(arr, 5, sizeof(int), pred_negative, NULL,
                           &idx, (const void**)&ep);
    EXPECT(!found);
    EXPECT(idx == 99);               /* output not written */
    EXPECT(ep == (const int*)0x1);   /* output not written */

    /* Typed slice */
    slice_int sv = slice_int_from(arr, 5);
    option_int opt = algo_find_slice_int(sv, pred_negative, NULL);
    EXPECT(!option_int_is_some(opt));

    usize i = algo_find_index_slice_int(sv, pred_negative, NULL);
    EXPECT(i == CANON_USIZE_MAX);
}

/* ── test_first_element ──────────────────────────────────────────────────── */
static void test_first_element(void)
{
    int arr[] = {-1, 2, 3, 4, 5};
    usize idx = 99;
    const int* ep = NULL;

    bool found = algo_find(arr, 5, sizeof(int), pred_negative, NULL,
                           &idx, (const void**)&ep);
    EXPECT(found);
    EXPECT(idx == 0);
    EXPECT(ep != NULL && *ep == -1);

    slice_int sv = slice_int_from(arr, 5);
    option_int opt = algo_find_slice_int(sv, pred_negative, NULL);
    EXPECT(option_int_is_some(opt) && option_int_unwrap(opt) == -1);

    usize i = algo_find_index_slice_int(sv, pred_negative, NULL);
    EXPECT(i == 0);
}

/* ── test_last_element ───────────────────────────────────────────────────── */
static void test_last_element(void)
{
    int arr[] = {1, 2, 3, 4, -5};
    usize idx = 99;
    const int* ep = NULL;

    bool found = algo_find(arr, 5, sizeof(int), pred_negative, NULL,
                           &idx, (const void**)&ep);
    EXPECT(found);
    EXPECT(idx == 4);
    EXPECT(ep != NULL && *ep == -5);

    slice_int sv = slice_int_from(arr, 5);
    option_int opt = algo_find_slice_int(sv, pred_negative, NULL);
    EXPECT(option_int_is_some(opt) && option_int_unwrap(opt) == -5);

    usize i = algo_find_index_slice_int(sv, pred_negative, NULL);
    EXPECT(i == 4);
}

/* ── test_middle_element ─────────────────────────────────────────────────── */
static void test_middle_element(void)
{
    int arr[] = {1, 2, -3, 4, 5};
    usize idx = 99;
    const int* ep = NULL;

    bool found = algo_find(arr, 5, sizeof(int), pred_negative, NULL,
                           &idx, (const void**)&ep);
    EXPECT(found);
    EXPECT(idx == 2);
    EXPECT(ep != NULL && *ep == -3);

    slice_int sv = slice_int_from(arr, 5);
    usize i = algo_find_index_slice_int(sv, pred_negative, NULL);
    EXPECT(i == 2);
}

/* ── test_first_match_wins ───────────────────────────────────────────────── */
static void test_first_match_wins(void)
{
    /* Multiple negatives — must return the first one */
    int arr[] = {1, -2, 3, -4, -5};
    usize idx = 99;
    const int* ep = NULL;

    bool found = algo_find(arr, 5, sizeof(int), pred_negative, NULL,
                           &idx, (const void**)&ep);
    EXPECT(found);
    EXPECT(idx == 1);
    EXPECT(ep != NULL && *ep == -2);

    slice_int sv = slice_int_from(arr, 5);
    option_int opt = algo_find_slice_int(sv, pred_negative, NULL);
    EXPECT(option_int_is_some(opt) && option_int_unwrap(opt) == -2);

    usize i = algo_find_index_slice_int(sv, pred_negative, NULL);
    EXPECT(i == 1);
}

/* ── test_null_outputs ───────────────────────────────────────────────────── */
static void test_null_outputs(void)
{
    int arr[] = {1, -2, 3};

    /* Both outputs NULL — still returns true/false correctly */
    bool found = algo_find(arr, 3, sizeof(int), pred_negative, NULL,
                           NULL, NULL);
    EXPECT(found);

    /* Index NULL only */
    const int* ep = NULL;
    found = algo_find(arr, 3, sizeof(int), pred_negative, NULL,
                      NULL, (const void**)&ep);
    EXPECT(found && ep != NULL && *ep == -2);

    /* Elem NULL only */
    usize idx = 99;
    found = algo_find(arr, 3, sizeof(int), pred_negative, NULL,
                      &idx, NULL);
    EXPECT(found && idx == 1);

    /* Not found, both NULL — safe */
    found = algo_find(arr, 3, sizeof(int), pred_always_false, NULL,
                      NULL, NULL);
    EXPECT(!found);
}

/* ── test_context_parameter ──────────────────────────────────────────────── */
static void test_context_parameter(void)
{
    int arr[] = {1, 5, 3, 8, 2};

    /* Find first element > 6 — should be 8 at index 3 */
    int threshold = 6;
    usize idx = 99;
    bool found = algo_find(arr, 5, sizeof(int), pred_gt_threshold, &threshold,
                           &idx, NULL);
    EXPECT(found && idx == 3);

    /* Find specific value */
    int target = 3;
    idx = 99;
    found = algo_find(arr, 5, sizeof(int), pred_eq_value, &target, &idx, NULL);
    EXPECT(found && idx == 2);

    /* Value not present */
    target = 99;
    found = algo_find(arr, 5, sizeof(int), pred_eq_value, &target, &idx, NULL);
    EXPECT(!found);
}

/* ── test_typed_macro ────────────────────────────────────────────────────── */
static void test_typed_macro(void)
{
    int arr[] = {10, 20, -30, 40};
    usize idx = 99;
    const int* ep = NULL;

    bool found = ALGO_FIND_TYPED(arr, 4, int, pred_negative, NULL, &idx, &ep);
    EXPECT(found && idx == 2 && ep != NULL && *ep == -30);

    /* Not found */
    idx = 99; ep = NULL;
    found = ALGO_FIND_TYPED(arr, 4, int, pred_always_false, NULL, &idx, &ep);
    EXPECT(!found && idx == 99 && ep == NULL);

    /* NULL outputs via typed macro */
    found = ALGO_FIND_TYPED(arr, 4, int, pred_negative, NULL, NULL, NULL);
    EXPECT(found);

    /* Empty */
    found = ALGO_FIND_TYPED(arr, 0, int, pred_negative, NULL, NULL, NULL);
    EXPECT(!found);
}

/* ── test_option_variant ─────────────────────────────────────────────────── */
static void test_option_variant(void)
{
    int arr[] = {5, 3, -2, -7, 1};
    slice_int sv = slice_int_from(arr, 5);

    /* Found: Some(-2) */
    option_int opt = algo_find_slice_int(sv, pred_negative, NULL);
    EXPECT(option_int_is_some(opt));
    EXPECT(option_int_unwrap(opt) == -2);

    /* Not found: None */
    int pos_arr[] = {1, 2, 3};
    slice_int sv2 = slice_int_from(pos_arr, 3);
    opt = algo_find_slice_int(sv2, pred_negative, NULL);
    EXPECT(!option_int_is_some(opt));

    /* Empty: None */
    slice_int empty = slice_int_empty();
    opt = algo_find_slice_int(empty, pred_negative, NULL);
    EXPECT(!option_int_is_some(opt));

    /* Single-element: found */
    int single[] = {-99};
    slice_int sv3 = slice_int_from(single, 1);
    opt = algo_find_slice_int(sv3, pred_negative, NULL);
    EXPECT(option_int_is_some(opt) && option_int_unwrap(opt) == -99);
}

/* ── test_index_variant ──────────────────────────────────────────────────── */
static void test_index_variant(void)
{
    int arr[] = {1, 2, -3, 4, -5};
    slice_int sv = slice_int_from(arr, 5);

    /* First negative at index 2 */
    usize i = algo_find_index_slice_int(sv, pred_negative, NULL);
    EXPECT(i == 2);

    /* Not found → CANON_USIZE_MAX */
    int pos[] = {1, 2, 3};
    slice_int sv2 = slice_int_from(pos, 3);
    i = algo_find_index_slice_int(sv2, pred_negative, NULL);
    EXPECT(i == CANON_USIZE_MAX);

    /* Empty → CANON_USIZE_MAX */
    slice_int empty = slice_int_empty();
    i = algo_find_index_slice_int(empty, pred_negative, NULL);
    EXPECT(i == CANON_USIZE_MAX);

    /* CANON_USIZE_MAX is never a valid index */
    EXPECT(CANON_USIZE_MAX > (usize)5); /* sanity: larger than any array used here */
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    Point arr[] = {{1, 2}, {3, 3}, {5, 4}, {7, 7}};
    slice_Point sv = slice_Point_from(arr, 4);

    /* Find first point where x == y: {3,3} at index 1 */
    option_Point opt = algo_find_slice_Point(sv, pred_point_eq, NULL);
    EXPECT(option_Point_is_some(opt));
    Point val = option_Point_unwrap(opt);
    EXPECT(val.x == 3 && val.y == 3);

    usize i = algo_find_index_slice_Point(sv, pred_point_eq, NULL);
    EXPECT(i == 1);

    /* None match */
    Point no_eq[] = {{1, 2}, {3, 4}};
    slice_Point sv2 = slice_Point_from(no_eq, 2);
    opt = algo_find_slice_Point(sv2, pred_point_eq, NULL);
    EXPECT(!option_Point_is_some(opt));

    i = algo_find_index_slice_Point(sv2, pred_point_eq, NULL);
    EXPECT(i == CANON_USIZE_MAX);

    /* Empty */
    slice_Point empty = slice_Point_empty();
    opt = algo_find_slice_Point(empty, pred_point_eq, NULL);
    EXPECT(!option_Point_is_some(opt));
}

/* ── test_short_circuit ──────────────────────────────────────────────────── */
static void test_short_circuit(void)
{
    /* Match at index 2 — pred called exactly 3 times */
    int arr[] = {1, 2, -3, -4, -5};
    g_call_count = 0;
    usize idx = 99;
    bool found = algo_find(arr, 5, sizeof(int), pred_negative_counting,
                           NULL, &idx, NULL);
    EXPECT(found && idx == 2);
    EXPECT(g_call_count == 3); /* checked 0, 1, 2 — stopped at 2 */

    /* No match — pred called for all 5 elements */
    int pos[] = {1, 2, 3, 4, 5};
    g_call_count = 0;
    found = algo_find(pos, 5, sizeof(int), pred_negative_counting,
                      NULL, NULL, NULL);
    EXPECT(!found);
    EXPECT(g_call_count == 5);

    /* Match at index 0 — pred called exactly once */
    int first_neg[] = {-9, 1, 2, 3, 4};
    g_call_count = 0;
    found = algo_find(first_neg, 5, sizeof(int), pred_negative_counting,
                      NULL, &idx, NULL);
    EXPECT(found && idx == 0);
    EXPECT(g_call_count == 1);
}

/* ── Suppress unused ─────────────────────────────────────────────────────── */
static void find_suppress_unused(void)
{
    (void)algo_find_slice_Point;
    (void)algo_find_index_slice_Point;
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)find_suppress_unused;
    (void)find_slice_suppress_unused;
    (void)find_option_suppress_unused;

    test_empty_sequence();
    test_not_found();
    test_first_element();
    test_last_element();
    test_middle_element();
    test_first_match_wins();
    test_null_outputs();
    test_context_parameter();
    test_typed_macro();
    test_option_variant();
    test_index_variant();
    test_point_struct();
    test_short_circuit();

    if (g_failed == 0) {
        printf("OK  find_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  find_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void find_fuzz_suppress_unused(void)
{
    (void)algo_find_slice_int;
    (void)algo_find_index_slice_int;
    (void)algo_find_slice_Point;
    (void)algo_find_index_slice_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz algo_find on a raw byte array.
 *
 * Predicate: first byte with value > 127.
 *
 * Invariants verified:
 *   1. found ↔ any byte > 127 exists
 *   2. if found: out_index == reference index
 *   3. if found: element at out_index satisfies pred
 *   4. if found: no element before out_index satisfies pred
 *   5. if not found: no element satisfies pred
 *   6. if not found: outputs unchanged (sentinel values preserved)
 */

static bool pred_high_byte(const void* elem, void* ctx)
{
    (void)ctx;
    return *(const u8*)elem > 127;
}

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)find_fuzz_suppress_unused;
    (void)find_slice_suppress_unused;
    (void)find_option_suppress_unused;

    /* Sentinel values — must not be overwritten on no-match */
    usize out_idx      = CANON_USIZE_MAX - 1;
    const void* out_ep = NULL;

    bool found = algo_find(data, size, sizeof(u8), pred_high_byte, NULL,
                           &out_idx, &out_ep);

    /* Build reference: index of first byte > 127 */
    usize ref_idx = CANON_USIZE_MAX;
    for (usize i = 0; i < size; i++) {
        if (data[i] > 127) { ref_idx = i; break; }
    }

    bool ref_found = (ref_idx != CANON_USIZE_MAX);

    /* Invariant 1: found ↔ reference found */
    if (found != ref_found) __builtin_trap();

    if (found) {
        /* Invariant 2: index matches reference */
        if (out_idx != ref_idx) __builtin_trap();

        /* Invariant 3: element at index satisfies pred */
        if (data[out_idx] <= 127) __builtin_trap();

        /* Invariant 4: no earlier element satisfies pred */
        for (usize i = 0; i < out_idx; i++) {
            if (data[i] > 127) __builtin_trap();
        }

        /* Invariant: out_ep points to correct element */
        if (out_ep != (const void*)(data + out_idx)) __builtin_trap();

    } else {
        /* Invariant 5: no element satisfies pred */
        for (usize i = 0; i < size; i++) {
            if (data[i] > 127) __builtin_trap();
        }

        /* Invariant 6: sentinels unchanged */
        if (out_idx != CANON_USIZE_MAX - 1) __builtin_trap();
        if (out_ep  != NULL)                 __builtin_trap();
    }

    return 0;
}

#endif /* CANON_FUZZING */
