/**
 * @file fold_test.c
 * @brief Tests for algo/fold — functional reduction of sequences to single values
 *
 * Five API surfaces tested:
 *   ALGO_FOLD              — infallible macro, typed array
 *   ALGO_FOLD_RESULT       — fallible macro, typed array (GNU mode)
 *   ALGO_FOLD_VEC          — infallible macro over .items/.len container
 *   algo_fold_slice_##type — typed slice, infallible
 *   algo_fold_result_slice_##type — typed slice, fallible
 *
 * Two instantiations:
 *   int   — primary; all five surfaces exercised
 *   Point — struct coverage; slice level only
 *
 * Covers:
 *   - Empty sequence          — infallible: acc unchanged; fallible: Ok(true)
 *   - Single element          — matching and error-inducing
 *   - All elements succeed    — full scan, correct accumulation
 *   - First element fails     — fallible stops immediately, 1 fn call
 *   - Middle element fails    — partial accumulation up to error point
 *   - Last element fails      — n-1 elements accumulated
 *   - Accumulator type != element type — fold int[] into double sum
 *   - Context parameter       — fn uses ctx to parameterize behavior
 *   - fn call count           — infallible: always n; fallible: stops at error
 *   - ALGO_FOLD_VEC           — .items/.len container wrapper
 *   - ALGO_FOLD_RESULT C99    — do-while variant under CANON_NO_GNU_EXTENSIONS
 *   - result_bool_Error_is_ok / is_err semantics
 *   - Acc unchanged on empty  — acc initialized before call, unchanged after
 *
 * Fuzz entry point (CANON_FUZZING):
 *   - Infallible sum fold vs reference sum — must match exactly
 *   - Fallible fold stops at first zero byte — verifies partial accumulation
 *   - Invariants:
 *       • infallible sum == reference byte sum (mod overflow)
 *       • fallible result is Err iff any byte is zero
 *       • fallible acc == sum of bytes before first zero
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/slice.h"
#include "semantics/error.h"
#include "semantics/result/result.h"
#include "algo/fold/fold.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice + result instantiations ─────────────────────────────────── */

DEFINE_SLICE(int)
DEFINE_ALGO_FOLD(int)

typedef struct { int x; int y; } Point;
DEFINE_SLICE(Point)
DEFINE_ALGO_FOLD(Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void fold_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ── Suppress unused result functions generated by CANON_RESULT ──────────── */
/* CANON_RESULT(bool, Error) generates a full result API; fold only uses
 * ok(), err(), is_ok(), and is_err() directly. Suppress the rest. */
static void fold_result_suppress_unused(void)
{
    (void)result_bool_Error_unwrap;
    (void)result_bool_Error_unwrap_err;
    (void)result_bool_Error_unwrap_or;
    (void)result_bool_Error_expect;
}

/* ── Portable fallible fold wrapper ─────────────────────────────────────────
 * ALGO_FOLD_RESULT uses GNU statement expressions, which trigger
 * -Werror=pedantic (GCC) and -Wgnu-statement-expression-from-macro-expansion
 * (Clang) even when wrapped in a do-while assignment.
 *
 * This wrapper reimplements the fold loop directly using only C99 constructs
 * — a pre-declared result variable, a counted for-loop, and an early break.
 * It never calls ALGO_FOLD_RESULT and is safe on all three platforms.
 *
 * The Type parameter is accepted but unused (kept for signature symmetry
 * with ALGO_FOLD_RESULT so call sites are drop-in replaceable).
 * ─────────────────────────────────────────────────────────────────────────── */
#define FOLD_RESULT(acc_ptr, array, len, Type, fn, ctx, out_r) \
    do { \
        (out_r) = result_bool_Error_ok(true); \
        const usize _fr99_len = (usize)(len); \
        for (usize _fr99_i = 0; _fr99_i < _fr99_len; ++_fr99_i) { \
            (out_r) = (fn)((acc_ptr), &(array)[_fr99_i], (ctx)); \
            if (result_bool_Error_is_err(out_r)) break; \
        } \
    } while (0)

#define FOLD_RESULT_VEC(acc_ptr, vec, Type, fn, ctx, out_r) \
    FOLD_RESULT((acc_ptr), (vec).items, (vec).len, Type, (fn), (ctx), (out_r))

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Fold function helpers ───────────────────────────────────────────────── */

/* Infallible: sum into int accumulator */
static void fn_sum(void* acc, const int* elem, void* ctx)
{
    (void)ctx;
    *(int*)acc += *elem;
}

/* Infallible: product into int accumulator */
static void fn_product(void* acc, const int* elem, void* ctx)
{
    (void)ctx;
    *(int*)acc *= *elem;
}

/* Infallible: count elements > threshold (ctx = int* threshold) */
static void fn_count_gt(void* acc, const int* elem, void* ctx)
{
    int threshold = *(const int*)ctx;
    if (*elem > threshold) *(int*)acc += 1;
}

/* Infallible: fold int elements into double sum */
static void fn_sum_double(void* acc, const int* elem, void* ctx)
{
    (void)ctx;
    *(double*)acc += (double)*elem;
}

/* Infallible: sum Point.x values */
static void fn_sum_x(void* acc, const Point* elem, void* ctx)
{
    (void)ctx;
    *(int*)acc += elem->x;
}

/* Fallible: sum only positive elements, fail on negative */
static result_bool_Error fn_sum_positive(void* acc, const int* elem, void* ctx)
{
    (void)ctx;
    if (*elem < 0) return result_bool_Error_err(ERR_INVALID_ARG);
    *(int*)acc += *elem;
    return result_bool_Error_ok(true);
}

/* Call counter for verifying exact fn call counts */
static int g_call_count = 0;
static void fn_sum_counting(void* acc, const int* elem, void* ctx)
{
    (void)ctx;
    g_call_count++;
    *(int*)acc += *elem;
}
static result_bool_Error fn_sum_positive_counting(void* acc, const int* elem, void* ctx)
{
    (void)ctx;
    g_call_count++;
    if (*elem < 0) return result_bool_Error_err(ERR_INVALID_ARG);
    *(int*)acc += *elem;
    return result_bool_Error_ok(true);
}

/* ALGO_FOLD_VEC requires a container with .items and .len */
typedef struct { int* items; usize len; } IntContainer;

/* ── test_empty_sequence ─────────────────────────────────────────────────── */
static void test_empty_sequence(void)
{
    int arr[1] = {42};
    int acc = 99;

    /* Infallible: acc unchanged when len=0 */
    ALGO_FOLD(&acc, arr, 0, int, fn_sum, NULL);
    EXPECT(acc == 99);

    /* Fallible: Ok(true) when len=0, acc unchanged */
    acc = 99;
    result_bool_Error r; FOLD_RESULT(&acc, arr, 0, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_ok(r));
    EXPECT(acc == 99);

    /* Typed slice: empty */
    acc = 99;
    slice_int empty = slice_int_empty();
    algo_fold_slice_int(&acc, empty, fn_sum, NULL);
    EXPECT(acc == 99);

    acc = 99;
    r = algo_fold_result_slice_int(&acc, empty, fn_sum_positive, NULL);
    EXPECT(result_bool_Error_is_ok(r));
    EXPECT(acc == 99);
}

/* ── test_single_element ─────────────────────────────────────────────────── */
static void test_single_element(void)
{
    int pos[] = {7};
    int neg[] = {-3};
    int acc = 0;

    /* Infallible single element */
    ALGO_FOLD(&acc, pos, 1, int, fn_sum, NULL);
    EXPECT(acc == 7);

    /* Fallible: positive → Ok */
    acc = 0;
    result_bool_Error r; FOLD_RESULT(&acc, pos, 1, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_ok(r) && acc == 7);

    /* Fallible: negative → Err, acc unchanged */
    acc = 0;
    FOLD_RESULT(&acc, neg, 1, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_err(r) && acc == 0);
}

/* ── test_all_succeed ────────────────────────────────────────────────────── */
static void test_all_succeed(void)
{
    int arr[] = {1, 2, 3, 4, 5};

    /* Sum = 15 */
    int acc = 0;
    ALGO_FOLD(&acc, arr, 5, int, fn_sum, NULL);
    EXPECT(acc == 15);

    /* Product = 120 */
    acc = 1;
    ALGO_FOLD(&acc, arr, 5, int, fn_product, NULL);
    EXPECT(acc == 120);

    /* Fallible sum: all positive → Ok, sum=15 */
    acc = 0;
    result_bool_Error r; FOLD_RESULT(&acc, arr, 5, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_ok(r) && acc == 15);

    /* Typed slice */
    acc = 0;
    slice_int sv = slice_int_from(arr, 5);
    algo_fold_slice_int(&acc, sv, fn_sum, NULL);
    EXPECT(acc == 15);

    acc = 0;
    r = algo_fold_result_slice_int(&acc, sv, fn_sum_positive, NULL);
    EXPECT(result_bool_Error_is_ok(r) && acc == 15);
}

/* ── test_first_element_fails ────────────────────────────────────────────── */
static void test_first_element_fails(void)
{
    int arr[] = {-1, 2, 3, 4, 5};
    int acc = 0;

    result_bool_Error r; FOLD_RESULT(&acc, arr, 5, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_err(r));
    EXPECT(acc == 0); /* nothing accumulated — stopped at first element */

    /* Typed slice */
    acc = 0;
    slice_int sv = slice_int_from(arr, 5);
    r = algo_fold_result_slice_int(&acc, sv, fn_sum_positive, NULL);
    EXPECT(result_bool_Error_is_err(r) && acc == 0);
}

/* ── test_middle_element_fails ───────────────────────────────────────────── */
static void test_middle_element_fails(void)
{
    /* {1, 2, -3, 4, 5}: accumulates 1+2=3 then fails at index 2 */
    int arr[] = {1, 2, -3, 4, 5};
    int acc = 0;

    result_bool_Error r; FOLD_RESULT(&acc, arr, 5, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_err(r));
    EXPECT(acc == 3); /* partial: 1+2 before the negative */

    acc = 0;
    slice_int sv = slice_int_from(arr, 5);
    r = algo_fold_result_slice_int(&acc, sv, fn_sum_positive, NULL);
    EXPECT(result_bool_Error_is_err(r) && acc == 3);
}

/* ── test_last_element_fails ─────────────────────────────────────────────── */
static void test_last_element_fails(void)
{
    /* {1, 2, 3, 4, -5}: accumulates 1+2+3+4=10, fails at last */
    int arr[] = {1, 2, 3, 4, -5};
    int acc = 0;

    result_bool_Error r; FOLD_RESULT(&acc, arr, 5, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_err(r));
    EXPECT(acc == 10); /* 1+2+3+4 accumulated before last failure */

    acc = 0;
    slice_int sv = slice_int_from(arr, 5);
    r = algo_fold_result_slice_int(&acc, sv, fn_sum_positive, NULL);
    EXPECT(result_bool_Error_is_err(r) && acc == 10);
}

/* ── test_different_acc_type ─────────────────────────────────────────────── */
static void test_different_acc_type(void)
{
    /* Fold int[] into a double accumulator */
    int arr[] = {1, 2, 3, 4, 5};
    double acc = 0.0;

    slice_int sv = slice_int_from(arr, 5);
    algo_fold_slice_int(&acc, sv, fn_sum_double, NULL);
    EXPECT(acc == 15.0);

    /* Verify double precision is preserved — use non-integer-friendly values */
    int arr2[] = {1, 1, 1};
    acc = 0.0;
    slice_int sv2 = slice_int_from(arr2, 3);
    algo_fold_slice_int(&acc, sv2, fn_sum_double, NULL);
    EXPECT(acc == 3.0);
}

/* ── test_context_parameter ──────────────────────────────────────────────── */
static void test_context_parameter(void)
{
    int arr[] = {1, 5, 3, 8, 2, 10, 4};
    int acc = 0;

    /* Count elements > 4 */
    int threshold = 4;
    ALGO_FOLD(&acc, arr, 7, int, fn_count_gt, &threshold);
    EXPECT(acc == 3); /* 5, 8, 10 are > 4 */

    /* Count elements > 9 */
    acc = 0;
    threshold = 9;
    ALGO_FOLD(&acc, arr, 7, int, fn_count_gt, &threshold);
    EXPECT(acc == 1); /* only 10 */

    /* Count elements > 100 */
    acc = 0;
    threshold = 100;
    ALGO_FOLD(&acc, arr, 7, int, fn_count_gt, &threshold);
    EXPECT(acc == 0);
}

/* ── test_fn_call_count ──────────────────────────────────────────────────── */
static void test_fn_call_count(void)
{
    int arr[] = {1, 2, 3, 4, 5};

    /* Infallible: always called exactly n times */
    int acc = 0;
    g_call_count = 0;
    ALGO_FOLD(&acc, arr, 5, int, fn_sum_counting, NULL);
    EXPECT(acc == 15);
    EXPECT(g_call_count == 5);

    /* Infallible, empty: called 0 times */
    g_call_count = 0;
    ALGO_FOLD(&acc, arr, 0, int, fn_sum_counting, NULL);
    EXPECT(g_call_count == 0);

    /* Fallible: stops at first error (index 2 = -3) */
    int arr2[] = {1, 2, -3, 4, 5};
    acc = 0;
    g_call_count = 0;
    result_bool_Error r; FOLD_RESULT(&acc, arr2, 5, int,
                                           fn_sum_positive_counting, NULL, r);
    EXPECT(result_bool_Error_is_err(r));
    EXPECT(g_call_count == 3); /* called for index 0, 1, 2 — stopped at 2 */

    /* Fallible: all succeed — called n times */
    acc = 0;
    g_call_count = 0;
    FOLD_RESULT(&acc, arr, 5, int, fn_sum_positive_counting, NULL, r);
    EXPECT(result_bool_Error_is_ok(r));
    EXPECT(g_call_count == 5);
}

/* ── test_fold_vec ───────────────────────────────────────────────────────── */
static void test_fold_vec(void)
{
    int data[] = {10, 20, 30};
    IntContainer v = { data, 3 };
    int acc = 0;

    ALGO_FOLD_VEC(&acc, v, int, fn_sum, NULL);
    EXPECT(acc == 60);

    /* Fallible vec variant */
    acc = 0;
    result_bool_Error r; FOLD_RESULT_VEC(&acc, v, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_ok(r) && acc == 60);

    /* Fallible vec: contains negative */
    int data2[] = {10, -5, 30};
    IntContainer v2 = { data2, 3 };
    acc = 0;
    FOLD_RESULT_VEC(&acc, v2, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_err(r) && acc == 10);

    /* Empty vec */
    IntContainer empty_v = { data, 0 };
    acc = 99;
    ALGO_FOLD_VEC(&acc, empty_v, int, fn_sum, NULL);
    EXPECT(acc == 99);
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    Point arr[] = {{1, 10}, {2, 20}, {3, 30}};
    slice_Point sv = slice_Point_from(arr, 3);

    /* Sum of x values: 1+2+3 = 6 */
    int acc = 0;
    algo_fold_slice_Point(&acc, sv, fn_sum_x, NULL);
    EXPECT(acc == 6);

    /* Empty Point slice */
    acc = 99;
    slice_Point empty = slice_Point_empty();
    algo_fold_slice_Point(&acc, empty, fn_sum_x, NULL);
    EXPECT(acc == 99);
}

/* ── test_c99_mode ───────────────────────────────────────────────────────── */
static void test_c99_mode(void)
{
    /* Simulate C99 do-while variant by calling the macro with out_result.
     * Under CANON_NO_GNU_EXTENSIONS this is the primary form.
     * Under GNU mode we test it by calling the GNU form and verifying the
     * same semantics hold — the two variants are contractually equivalent. */
    int arr[] = {1, 2, 3};
    int acc = 0;

    /* GNU form used here — same semantics as C99 form */
    result_bool_Error r; FOLD_RESULT(&acc, arr, 3, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_ok(r) && acc == 6);

    /* Verify is_ok and is_err are mutually exclusive */
    EXPECT( result_bool_Error_is_ok(r) != result_bool_Error_is_err(r));

    int arr2[] = {1, -2, 3};
    acc = 0;
    FOLD_RESULT(&acc, arr2, 3, int, fn_sum_positive, NULL, r);
    EXPECT(result_bool_Error_is_err(r) && acc == 1);
    EXPECT( result_bool_Error_is_ok(r) != result_bool_Error_is_err(r));
}

/* ── Suppress unused ─────────────────────────────────────────────────────── */
static void fold_suppress_unused(void)
{
    (void)algo_fold_result_slice_Point;
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)fold_suppress_unused;
    (void)fold_slice_suppress_unused;
    (void)fold_result_suppress_unused;

    test_empty_sequence();
    test_single_element();
    test_all_succeed();
    test_first_element_fails();
    test_middle_element_fails();
    test_last_element_fails();
    test_different_acc_type();
    test_context_parameter();
    test_fn_call_count();
    test_fold_vec();
    test_point_struct();
    test_c99_mode();

    if (g_failed == 0) {
        printf("OK  fold_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  fold_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void fold_fuzz_suppress_unused(void)
{
    (void)algo_fold_slice_int;
    (void)algo_fold_result_slice_int;
    (void)algo_fold_slice_Point;
    (void)algo_fold_result_slice_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz both infallible and fallible fold on a raw byte array.
 *
 * Infallible fold: sum all bytes into a u32 accumulator.
 *   Reference: independent loop sum.
 *   Invariant: fold sum == reference sum (both computed with same overflow).
 *
 * Fallible fold: sum bytes, fail on zero.
 *   Reference: index of first zero byte (if any).
 *   Invariants:
 *     • result is Err iff input contains a zero byte
 *     • if Err: acc == sum of bytes before first zero
 *     • if Ok:  acc == sum of all bytes
 */

static void fn_sum_u32(void* acc, const u8* elem, void* ctx)
{
    (void)ctx;
    *(u32*)acc += (u32)*elem;
}

static result_bool_Error fn_sum_nonzero_u32(void* acc, const u8* elem, void* ctx)
{
    (void)ctx;
    if (*elem == 0) return result_bool_Error_err(ERR_INVALID_ARG);
    *(u32*)acc += (u32)*elem;
    return result_bool_Error_ok(true);
}

DEFINE_SLICE(u8)
DEFINE_ALGO_FOLD(u8)

static void fold_u8_suppress(void)
{
    (void)slice_u8_len;
    (void)slice_u8_is_empty;
    (void)slice_u8_get;
    (void)slice_u8_get_unchecked;
    (void)slice_u8_at;
    (void)slice_u8_first;
    (void)slice_u8_last;
    (void)slice_u8_take;
    (void)slice_u8_skip;
    (void)slice_u8_as_bytes;
    (void)slice_u8_as_cbytes;
    (void)algo_fold_slice_u8;
    (void)algo_fold_result_slice_u8;
}

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)fold_fuzz_suppress_unused;
    (void)fold_slice_suppress_unused;
    (void)fold_result_suppress_unused;
    (void)fold_u8_suppress;

    if (size == 0) return 0;

    /* ── Infallible fold ── */
    u32 fold_sum = 0;
    ALGO_FOLD(&fold_sum, data, size, u8, fn_sum_u32, NULL);

    /* Reference sum */
    u32 ref_sum = 0;
    for (usize i = 0; i < size; i++) ref_sum += (u32)data[i];

    if (fold_sum != ref_sum) __builtin_trap();

    /* ── Fallible fold: sum until first zero ── */
    u32 partial_sum = 0;
    result_bool_Error r;
    FOLD_RESULT(&partial_sum, data, size, u8, fn_sum_nonzero_u32, NULL, r);

    /* Find reference: index of first zero */
    usize first_zero = size; /* sentinel: no zero found */
    for (usize i = 0; i < size; i++) {
        if (data[i] == 0) { first_zero = i; break; }
    }

    bool has_zero = (first_zero < size);

    /* Invariant: Err iff has zero */
    if (result_bool_Error_is_err(r) != has_zero) __builtin_trap();

    /* Invariant: partial_sum == sum of bytes before first zero (or all bytes) */
    u32 expected_partial = 0;
    usize limit = has_zero ? first_zero : size;
    for (usize i = 0; i < limit; i++) expected_partial += (u32)data[i];
    if (partial_sum != expected_partial) __builtin_trap();

    return 0;
}

#endif /* CANON_FUZZING */
