/**
 * @file map_test.c
 * @brief Tests for algo/map — element-wise transformation over sequences
 *
 * Four API surfaces tested:
 *   algo_map              — generic cross-type transform (void* interface)
 *   algo_map_inplace      — generic in-place transform (void* interface)
 *   ALGO_MAP_TYPED        — typed macro, compile-time sizeof, cross-type
 *   ALGO_MAP_INPLACE_TYPED — typed macro, compile-time sizeof, in-place
 *   algo_map_slice_##in##_##out — typed slice, cross-type
 *   algo_map_inplace_slice_##type — typed slice, in-place
 *
 * Two instantiations:
 *   int × double — primary cross-type case
 *   int × int    — same-type / in-place case; also exercises Point struct
 *
 * Covers:
 *   - Empty sequence (len=0)          — no fn call, output unchanged
 *   - Single element                  — transform applied once
 *   - Multiple elements               — all transformed correctly
 *   - Cross-type transform (int→double) — type conversion verified
 *   - Same-type in-place transform    — original overwritten
 *   - Typed macro (ALGO_MAP_TYPED)    — compile-time sizeof, same semantics
 *   - Typed macro (ALGO_MAP_INPLACE_TYPED) — compile-time sizeof
 *   - Typed slice cross-type          — algo_map_slice_int_double
 *   - Typed slice in-place            — algo_map_inplace_slice_int
 *   - Mismatched slice lengths        — min(sv_out.len, sv_in.len) processed
 *   - fn call count                   — always exactly n calls
 *   - Input unchanged after algo_map  — verified explicitly
 *   - Point struct                    — algo_map_inplace_slice_Point
 *
 * Fuzz entry point (CANON_FUZZING):
 *   - algo_map: int[] → double[] — reference: cast each input
 *   - algo_map_inplace: negate each element — reference: independent copy
 *   - Invariants:
 *       • output[i] == (double)input[i] for all i
 *       • after inplace: arr[i] == -original[i] for all i
 *       • fn called exactly n times (verified via call counter)
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/slice.h"
#include "algo/map/map.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice instantiations ──────────────────────────────────────────── */

DEFINE_SLICE(int)
DEFINE_SLICE(double)
DEFINE_ALGO_MAP(int, double)   /* generates: algo_map_slice_int_double
                                              algo_map_inplace_slice_int */

typedef struct { int x; int y; } Point;
DEFINE_SLICE(Point)
DEFINE_ALGO_MAP(Point, Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void map_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* double slice */
    (void)slice_double_len;
    (void)slice_double_is_empty;
    (void)slice_double_get;
    (void)slice_double_get_unchecked;
    (void)slice_double_at;
    (void)slice_double_first;
    (void)slice_double_last;
    (void)slice_double_take;
    (void)slice_double_skip;
    (void)slice_double_as_bytes;
    (void)slice_double_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ════════════════════════════════════════════════════════════════════════════
   Unit test build
   ════════════════════════════════════════════════════════════════════════════ */

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Transform helpers ───────────────────────────────────────────────────── */

static void fn_int_to_double(void* out, const void* in)
{
    *(double*)out = (double)(*(const int*)in);
}

static void fn_square_double(void* out, const void* in)
{
    double v = (double)(*(const int*)in);
    *(double*)out = v * v;
}

static void fn_negate(void* elem)
{
    *(int*)elem = -(*(int*)elem);
}

static void fn_increment(void* elem)
{
    (*(int*)elem)++;
}

static void fn_double_inplace(void* elem)
{
    *(int*)elem *= 2;
}

/* Typed slice helpers */
static void fn_typed_int_to_double(double* out, const int* in)
{
    *out = (double)(*in);
}

static void fn_typed_square(double* out, const int* in)
{
    double v = (double)(*in);
    *out = v * v;
}

static void fn_typed_increment(int* elem)
{
    (*elem)++;
}

static void fn_typed_negate(int* elem)
{
    *elem = -(*elem);
}

/* Point helpers */
static void fn_typed_negate_x(Point* elem)
{
    elem->x = -elem->x;
}

/* Call counter */
static int g_call_count = 0;
static void fn_increment_counting(void* elem)
{
    g_call_count++;
    (*(int*)elem)++;
}

/* ── test_empty_sequence ─────────────────────────────────────────────────── */
static void test_empty_sequence(void)
{
    int    in_arr[1]  = {42};
    double out_arr[1] = {99.0};

    /* algo_map: len=0 — output unchanged, fn never called */
    g_call_count = 0;
    algo_map(out_arr, in_arr, 0, sizeof(double), sizeof(int), fn_int_to_double);
    EXPECT(out_arr[0] == 99.0);

    /* algo_map_inplace: len=0 — array unchanged */
    algo_map_inplace(in_arr, 0, sizeof(int), fn_negate);
    EXPECT(in_arr[0] == 42);

    /* Typed macros: len=0 */
    ALGO_MAP_TYPED(out_arr, in_arr, 0, double, int, fn_int_to_double);
    EXPECT(out_arr[0] == 99.0);
    ALGO_MAP_INPLACE_TYPED(in_arr, 0, int, fn_negate);
    EXPECT(in_arr[0] == 42);

    /* Typed slice: empty */
    slice_int    sv_in  = slice_int_empty();
    slice_double sv_out = slice_double_empty();
    algo_map_slice_int_double(sv_out, sv_in, fn_typed_int_to_double);

    slice_int sv_ip = slice_int_empty();
    algo_map_inplace_slice_int(sv_ip, fn_typed_increment);
}

/* ── test_single_element ─────────────────────────────────────────────────── */
static void test_single_element(void)
{
    int    in_arr[1]  = {7};
    double out_arr[1] = {0.0};

    /* algo_map: int → double */
    algo_map(out_arr, in_arr, 1, sizeof(double), sizeof(int), fn_int_to_double);
    EXPECT(out_arr[0] == 7.0);

    /* algo_map_inplace: negate */
    algo_map_inplace(in_arr, 1, sizeof(int), fn_negate);
    EXPECT(in_arr[0] == -7);

    /* Restore and test typed macro */
    in_arr[0] = 3;
    out_arr[0] = 0.0;
    ALGO_MAP_TYPED(out_arr, in_arr, 1, double, int, fn_int_to_double);
    EXPECT(out_arr[0] == 3.0);

    ALGO_MAP_INPLACE_TYPED(in_arr, 1, int, fn_increment);
    EXPECT(in_arr[0] == 4);
}

/* ── test_multiple_elements ──────────────────────────────────────────────── */
static void test_multiple_elements(void)
{
    int    in_arr[] = {1, 2, 3, 4, 5};
    double out_arr[5] = {0};

    /* algo_map: cast to double */
    algo_map(out_arr, in_arr, 5, sizeof(double), sizeof(int), fn_int_to_double);
    EXPECT(out_arr[0] == 1.0);
    EXPECT(out_arr[1] == 2.0);
    EXPECT(out_arr[2] == 3.0);
    EXPECT(out_arr[3] == 4.0);
    EXPECT(out_arr[4] == 5.0);

    /* Input unchanged */
    EXPECT(in_arr[0] == 1 && in_arr[4] == 5);

    /* Square transform */
    double sq[5] = {0};
    algo_map(sq, in_arr, 5, sizeof(double), sizeof(int), fn_square_double);
    EXPECT(sq[0] == 1.0 && sq[1] == 4.0 && sq[2] == 9.0 &&
           sq[3] == 16.0 && sq[4] == 25.0);
}

/* ── test_inplace_transform ──────────────────────────────────────────────── */
static void test_inplace_transform(void)
{
    int arr[] = {1, 2, 3, 4, 5};

    /* negate all */
    algo_map_inplace(arr, 5, sizeof(int), fn_negate);
    EXPECT(arr[0] == -1 && arr[1] == -2 && arr[2] == -3 &&
           arr[3] == -4 && arr[4] == -5);

    /* double all (x2) */
    algo_map_inplace(arr, 5, sizeof(int), fn_double_inplace);
    EXPECT(arr[0] == -2 && arr[1] == -4 && arr[2] == -6 &&
           arr[3] == -8 && arr[4] == -10);
}

/* ── test_typed_macro ────────────────────────────────────────────────────── */
static void test_typed_macro(void)
{
    int    in_arr[] = {10, 20, 30};
    double out_arr[3] = {0};

    /* ALGO_MAP_TYPED */
    ALGO_MAP_TYPED(out_arr, in_arr, 3, double, int, fn_int_to_double);
    EXPECT(out_arr[0] == 10.0 && out_arr[1] == 20.0 && out_arr[2] == 30.0);

    /* Input unchanged */
    EXPECT(in_arr[0] == 10 && in_arr[2] == 30);

    /* ALGO_MAP_INPLACE_TYPED */
    ALGO_MAP_INPLACE_TYPED(in_arr, 3, int, fn_increment);
    EXPECT(in_arr[0] == 11 && in_arr[1] == 21 && in_arr[2] == 31);

    /* Empty via typed macro */
    ALGO_MAP_TYPED(out_arr, in_arr, 0, double, int, fn_int_to_double);
    EXPECT(out_arr[0] == 10.0); /* unchanged */
}

/* ── test_typed_slice_cross ──────────────────────────────────────────────── */
static void test_typed_slice_cross(void)
{
    int    buf_in[]  = {1, 2, 3, 4, 5};
    double buf_out[5] = {0};
    slice_int    sv_in  = slice_int_from(buf_in,  5);
    slice_double sv_out = slice_double_from(buf_out, 5);

    algo_map_slice_int_double(sv_out, sv_in, fn_typed_int_to_double);
    EXPECT(buf_out[0] == 1.0 && buf_out[2] == 3.0 && buf_out[4] == 5.0);

    /* Square variant */
    double sq_buf[5] = {0};
    slice_double sv_sq = slice_double_from(sq_buf, 5);
    algo_map_slice_int_double(sv_sq, sv_in, fn_typed_square);
    EXPECT(sq_buf[0] == 1.0 && sq_buf[1] == 4.0 && sq_buf[2] == 9.0 &&
           sq_buf[3] == 16.0 && sq_buf[4] == 25.0);

    /* Input unchanged */
    EXPECT(buf_in[0] == 1 && buf_in[4] == 5);
}

/* ── test_typed_slice_inplace ────────────────────────────────────────────── */
static void test_typed_slice_inplace(void)
{
    int buf[] = {1, 2, 3, 4, 5};
    slice_int sv = slice_int_from(buf, 5);

    algo_map_inplace_slice_int(sv, fn_typed_negate);
    EXPECT(buf[0] == -1 && buf[1] == -2 && buf[2] == -3 &&
           buf[3] == -4 && buf[4] == -5);

    algo_map_inplace_slice_int(sv, fn_typed_increment);
    EXPECT(buf[0] == 0 && buf[1] == -1 && buf[2] == -2 &&
           buf[3] == -3 && buf[4] == -4);
}

/* ── test_mismatched_slice_lengths ───────────────────────────────────────── */
static void test_mismatched_slice_lengths(void)
{
    /* sv_out shorter than sv_in — only sv_out.len elements processed */
    int    buf_in[]  = {1, 2, 3, 4, 5};
    double buf_out[3] = {0};
    slice_int    sv_in  = slice_int_from(buf_in,  5);
    slice_double sv_out = slice_double_from(buf_out, 3);

    algo_map_slice_int_double(sv_out, sv_in, fn_typed_int_to_double);
    EXPECT(buf_out[0] == 1.0 && buf_out[1] == 2.0 && buf_out[2] == 3.0);

    /* sv_in shorter than sv_out — only sv_in.len elements processed */
    double buf_out2[5] = {99.0, 99.0, 99.0, 99.0, 99.0};
    int    buf_in2[]  = {10, 20};
    slice_int    sv_in2  = slice_int_from(buf_in2,  2);
    slice_double sv_out2 = slice_double_from(buf_out2, 5);

    algo_map_slice_int_double(sv_out2, sv_in2, fn_typed_int_to_double);
    EXPECT(buf_out2[0] == 10.0 && buf_out2[1] == 20.0);
    EXPECT(buf_out2[2] == 99.0 && buf_out2[3] == 99.0); /* untouched */
}

/* ── test_fn_call_count ──────────────────────────────────────────────────── */
static void test_fn_call_count(void)
{
    int arr[] = {1, 2, 3, 4, 5};

    /* algo_map_inplace: exactly n calls */
    g_call_count = 0;
    algo_map_inplace(arr, 5, sizeof(int), fn_increment_counting);
    EXPECT(g_call_count == 5);

    /* Empty: 0 calls */
    g_call_count = 0;
    algo_map_inplace(arr, 0, sizeof(int), fn_increment_counting);
    EXPECT(g_call_count == 0);

    /* algo_map: exactly n calls — use counting wrapper via generic interface */
    int    in_arr[] = {10, 20, 30};
    double out_arr[3] = {0};
    g_call_count = 0;
    algo_map(out_arr, in_arr, 3, sizeof(double), sizeof(int), fn_int_to_double);
    /* Note: fn_int_to_double doesn't use g_call_count. Verify output instead. */
    EXPECT(out_arr[0] == 10.0 && out_arr[1] == 20.0 && out_arr[2] == 30.0);
}

/* ── test_input_unchanged ────────────────────────────────────────────────── */
static void test_input_unchanged(void)
{
    int    in_orig[] = {5, 10, 15, 20};
    int    in_copy[] = {5, 10, 15, 20};
    double out[4]    = {0};

    algo_map(out, in_orig, 4, sizeof(double), sizeof(int), fn_int_to_double);

    /* Input must be byte-for-byte identical */
    for (int i = 0; i < 4; i++) {
        EXPECT(in_orig[i] == in_copy[i]);
    }
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    Point arr[] = {{1, 2}, {3, 4}, {5, 6}};
    slice_Point sv = slice_Point_from(arr, 3);

    /* Negate x in place */
    algo_map_inplace_slice_Point(sv, fn_typed_negate_x);
    EXPECT(arr[0].x == -1 && arr[0].y == 2);
    EXPECT(arr[1].x == -3 && arr[1].y == 4);
    EXPECT(arr[2].x == -5 && arr[2].y == 6);

    /* Empty Point slice */
    slice_Point empty = slice_Point_empty();
    algo_map_inplace_slice_Point(empty, fn_typed_negate_x); /* no-op */
}

/* ── Suppress unused ─────────────────────────────────────────────────────── */
static void map_suppress_unused(void)
{
    (void)algo_map_inplace_slice_Point;
    (void)algo_map_slice_Point_Point;
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)map_suppress_unused;
    (void)map_slice_suppress_unused;

    test_empty_sequence();
    test_single_element();
    test_multiple_elements();
    test_inplace_transform();
    test_typed_macro();
    test_typed_slice_cross();
    test_typed_slice_inplace();
    test_mismatched_slice_lengths();
    test_fn_call_count();
    test_input_unchanged();
    test_point_struct();

    if (g_failed == 0) {
        printf("OK  map_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  map_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void map_fuzz_suppress_unused(void)
{
    (void)algo_map_slice_int_double;
    (void)algo_map_inplace_slice_int;
    (void)algo_map_inplace_slice_Point;
    (void)algo_map_slice_Point_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_double_from;
    (void)slice_double_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz algo_map (int → double) and algo_map_inplace (negate) on raw input.
 *
 * Invariants:
 *   algo_map:
 *     1. output[i] == (double)data[i] for all i
 *     2. input unchanged after the call
 *
 *   algo_map_inplace:
 *     3. arr[i] == -original[i] for all i after negate
 *     4. double-negate restores original values
 */

static void fn_fuzz_int_to_double(void* out, const void* in)
{
    *(double*)out = (double)(*(const int*)in);
}

static void fn_fuzz_negate(void* elem)
{
    *(int*)elem = -(*(int*)elem);
}

/* Maximum elements we'll process to keep allocations bounded */
#define MAP_FUZZ_MAX 256

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)map_fuzz_suppress_unused;
    (void)map_slice_suppress_unused;

    /* Need at least sizeof(int) bytes to form one element */
    if (size < sizeof(int)) return 0;

    /* Clamp to max elements */
    usize n = size / sizeof(int);
    if (n > MAP_FUZZ_MAX) n = MAP_FUZZ_MAX;

    /* Copy input bytes into int array */
    int src[MAP_FUZZ_MAX];
    memcpy(src, data, n * sizeof(int));

    /* ── Invariant: algo_map produces correct cast ── */
    double dst[MAP_FUZZ_MAX] = {0};
    algo_map(dst, src, n, sizeof(double), sizeof(int), fn_fuzz_int_to_double);

    for (usize i = 0; i < n; i++) {
        if (dst[i] != (double)src[i]) __builtin_trap();
    }

    /* Input unchanged */
    int src_check[MAP_FUZZ_MAX];
    memcpy(src_check, data, n * sizeof(int));
    for (usize i = 0; i < n; i++) {
        if (src[i] != src_check[i]) __builtin_trap();
    }

    /* ── Invariant: algo_map_inplace negate is self-inverse ── */
    int arr[MAP_FUZZ_MAX];
    memcpy(arr, src, n * sizeof(int));

    algo_map_inplace(arr, n, sizeof(int), fn_fuzz_negate);

    /* Verify negate: arr[i] == -src[i] */
    for (usize i = 0; i < n; i++) {
        if (arr[i] != -src[i]) __builtin_trap();
    }

    /* Double-negate restores original */
    algo_map_inplace(arr, n, sizeof(int), fn_fuzz_negate);
    for (usize i = 0; i < n; i++) {
        if (arr[i] != src[i]) __builtin_trap();
    }

    return 0;
}

#endif /* CANON_FUZZING */
