/**
 * @file reverse_test.c 
 * @brief Tests for algo/reverse — in-place reversal and palindrome checking
 *
 * Two algorithms, three API levels each:
 *   algo_reverse           — generic in-place reversal (void* interface)
 *   ALGO_REVERSE_TYPED     — typed macro, compile-time sizeof
 *   algo_reverse_slice_##type — typed slice
 *
 *   algo_is_palindrome         — generic palindrome check (void* interface)
 *   ALGO_IS_PALINDROME_TYPED   — typed macro, compile-time sizeof
 *   algo_is_palindrome_slice_##type — typed slice
 *
 * Two instantiations:
 *   int   — primary; all three levels exercised
 *   Point — struct coverage; slice level only
 *
 * Covers:
 *   - Empty (len=0)            — reverse: no-op; palindrome: true
 *   - Single element (len=1)   — reverse: no-op; palindrome: true
 *   - Even length              — even pair count, no center element
 *   - Odd length               — center element stays in place
 *   - Already reversed         — reverse twice = identity
 *   - True palindrome          — palindrome returns true
 *   - Non-palindrome           — palindrome returns false
 *   - First pair mismatch      — palindrome short-circuits at pair 0
 *   - Last pair mismatch       — palindrome short-circuits near center
 *   - Typed macro              — ALGO_REVERSE_TYPED / ALGO_IS_PALINDROME_TYPED
 *   - Typed slice              — algo_reverse_slice_int / algo_is_palindrome_slice_int
 *   - Point struct             — algo_reverse_slice_Point / algo_is_palindrome_slice_Point
 *   - Context parameter        — cmp uses ctx for threshold
 *   - Dual relationship        — reverse then palindrome check on known results
 *
 * Fuzz entry point (CANON_FUZZING):
 *   - algo_reverse is self-inverse: reverse twice = original
 *   - algo_is_palindrome after reverse: must equal palindrome check on original
 *   - Invariants:
 *       • double-reverse restores original byte-for-byte
 *       • is_palindrome(arr) == is_palindrome(reverse(arr))
 *         (palindrome status is invariant under reversal)
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/primitives/compare.h"
#include "core/slice.h"
#include "algo/reverse/reverse.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice instantiations ──────────────────────────────────────────── */

DEFINE_SLICE(int)
DEFINE_ALGO_REVERSE(int)

typedef struct { int x; int y; } Point;
DEFINE_SLICE(Point)
DEFINE_ALGO_REVERSE(Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void reverse_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ════════════════════════════════════════════════════════════════════════════
   Unit test build
   ════════════════════════════════════════════════════════════════════════════ */

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Comparator helpers ──────────────────────────────────────────────────── */

static int cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    return *(const int*)a - *(const int*)b;
}

/* Context-parameterized: returns 0 only when both values exceed threshold */
static int cmp_int_threshold(const void* a, const void* b, void* ctx)
{
    int threshold = *(const int*)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    /* treat both values as equal iff they are both > threshold */
    int a_over = (va > threshold) ? 1 : 0;
    int b_over = (vb > threshold) ? 1 : 0;
    return a_over - b_over;
}

static int cmp_point_x(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    return ((const Point*)a)->x - ((const Point*)b)->x;
}

/* ── test_empty ──────────────────────────────────────────────────────────── */
static void test_empty(void)
{
    int arr[1] = {42};

    /* algo_reverse: len=0 — no-op */
    algo_reverse(arr, 0, sizeof(int));
    EXPECT(arr[0] == 42);

    /* algo_is_palindrome: len=0 — vacuous true */
    EXPECT(algo_is_palindrome(arr, 0, sizeof(int), cmp_int, NULL) == true);

    /* Typed macro */
    ALGO_REVERSE_TYPED(arr, 0, int);
    EXPECT(arr[0] == 42);
    EXPECT(ALGO_IS_PALINDROME_TYPED(arr, 0, int, cmp_int, NULL) == true);

    /* Typed slice */
    slice_int empty = slice_int_empty();
    algo_reverse_slice_int(empty);          /* no-op */
    EXPECT(algo_is_palindrome_slice_int(empty, cmp_int, NULL) == true);
}

/* ── test_single_element ─────────────────────────────────────────────────── */
static void test_single_element(void)
{
    int arr[1] = {99};

    algo_reverse(arr, 1, sizeof(int));
    EXPECT(arr[0] == 99);

    EXPECT(algo_is_palindrome(arr, 1, sizeof(int), cmp_int, NULL) == true);

    ALGO_REVERSE_TYPED(arr, 1, int);
    EXPECT(arr[0] == 99);
    EXPECT(ALGO_IS_PALINDROME_TYPED(arr, 1, int, cmp_int, NULL) == true);

    slice_int sv = slice_int_from(arr, 1);
    algo_reverse_slice_int(sv);
    EXPECT(arr[0] == 99);
    EXPECT(algo_is_palindrome_slice_int(sv, cmp_int, NULL) == true);
}

/* ── test_even_length ────────────────────────────────────────────────────── */
static void test_even_length(void)
{
    int arr[] = {1, 2, 3, 4};

    algo_reverse(arr, 4, sizeof(int));
    EXPECT(arr[0] == 4 && arr[1] == 3 && arr[2] == 2 && arr[3] == 1);

    /* Reverse again → back to original */
    algo_reverse(arr, 4, sizeof(int));
    EXPECT(arr[0] == 1 && arr[1] == 2 && arr[2] == 3 && arr[3] == 4);
}

/* ── test_odd_length ─────────────────────────────────────────────────────── */
static void test_odd_length(void)
{
    int arr[] = {1, 2, 3, 4, 5};

    algo_reverse(arr, 5, sizeof(int));
    EXPECT(arr[0] == 5 && arr[1] == 4 && arr[2] == 3 &&
           arr[3] == 2 && arr[4] == 1);

    /* Center element stays in place */
    EXPECT(arr[2] == 3);
}

/* ── test_double_reverse_identity ────────────────────────────────────────── */
static void test_double_reverse_identity(void)
{
    int original[] = {10, 20, 30, 40, 50, 60};
    int arr[]      = {10, 20, 30, 40, 50, 60};

    algo_reverse(arr, 6, sizeof(int));
    algo_reverse(arr, 6, sizeof(int));

    for (int i = 0; i < 6; i++) {
        EXPECT(arr[i] == original[i]);
    }
}

/* ── test_palindrome_true ────────────────────────────────────────────────── */
static void test_palindrome_true(void)
{
    /* Odd-length palindrome */
    int odd[] = {1, 2, 3, 2, 1};
    EXPECT(algo_is_palindrome(odd, 5, sizeof(int), cmp_int, NULL) == true);

    /* Even-length palindrome */
    int even[] = {1, 2, 2, 1};
    EXPECT(algo_is_palindrome(even, 4, sizeof(int), cmp_int, NULL) == true);

    /* Single-element */
    int single[] = {7};
    EXPECT(algo_is_palindrome(single, 1, sizeof(int), cmp_int, NULL) == true);

    /* All same */
    int same[] = {5, 5, 5, 5, 5};
    EXPECT(algo_is_palindrome(same, 5, sizeof(int), cmp_int, NULL) == true);
}

/* ── test_palindrome_false ───────────────────────────────────────────────── */
static void test_palindrome_false(void)
{
    /* First and last differ */
    int arr1[] = {1, 2, 3, 2, 2};
    EXPECT(algo_is_palindrome(arr1, 5, sizeof(int), cmp_int, NULL) == false);

    /* Middle pair differs */
    int arr2[] = {1, 3, 3, 2, 1};
    EXPECT(algo_is_palindrome(arr2, 5, sizeof(int), cmp_int, NULL) == false);

    /* Two-element non-equal */
    int arr3[] = {1, 2};
    EXPECT(algo_is_palindrome(arr3, 2, sizeof(int), cmp_int, NULL) == false);
}

/* ── test_palindrome_short_circuit ───────────────────────────────────────── */
static void test_palindrome_short_circuit(void)
{
    /* Mismatch at pair 0 (first and last) — should stop immediately */
    int arr[] = {1, 2, 3, 4, 5};
    /* First pair: arr[0]=1 vs arr[4]=5 — mismatch */
    EXPECT(algo_is_palindrome(arr, 5, sizeof(int), cmp_int, NULL) == false);

    /* Mismatch only at last pair (near center) */
    int arr2[] = {1, 2, 3, 2, 2};
    /* Pairs: (1,2)=mismatch at pair 0 — returns immediately */
    EXPECT(algo_is_palindrome(arr2, 5, sizeof(int), cmp_int, NULL) == false);

    /* Verify a near-palindrome where only center-adjacent pair fails */
    int arr3[] = {5, 5, 1, 2, 5, 5};
    /* Pairs: (5,5)=ok, (5,5)=ok, (1,2)=fail */
    EXPECT(algo_is_palindrome(arr3, 6, sizeof(int), cmp_int, NULL) == false);
}

/* ── test_typed_macro ────────────────────────────────────────────────────── */
static void test_typed_macro(void)
{
    int arr[] = {1, 2, 3, 4, 5};

    ALGO_REVERSE_TYPED(arr, 5, int);
    EXPECT(arr[0] == 5 && arr[2] == 3 && arr[4] == 1);

    ALGO_REVERSE_TYPED(arr, 5, int);
    EXPECT(arr[0] == 1 && arr[2] == 3 && arr[4] == 5);

    int pal[] = {7, 3, 7};
    EXPECT(ALGO_IS_PALINDROME_TYPED(pal, 3, int, cmp_int, NULL) == true);

    int notpal[] = {7, 3, 8};
    EXPECT(ALGO_IS_PALINDROME_TYPED(notpal, 3, int, cmp_int, NULL) == false);
}

/* ── test_typed_slice ────────────────────────────────────────────────────── */
static void test_typed_slice(void)
{
    int buf[] = {1, 2, 3, 4, 5};
    slice_int sv = slice_int_from(buf, 5);

    algo_reverse_slice_int(sv);
    EXPECT(buf[0] == 5 && buf[2] == 3 && buf[4] == 1);

    /* Palindrome check on reversed buffer */
    EXPECT(algo_is_palindrome_slice_int(sv, cmp_int, NULL) == false);

    /* Reverse back */
    algo_reverse_slice_int(sv);
    EXPECT(buf[0] == 1 && buf[2] == 3 && buf[4] == 5);

    /* True palindrome via slice */
    int pal_buf[] = {3, 1, 4, 1, 3};
    slice_int sv_pal = slice_int_from(pal_buf, 5);
    EXPECT(algo_is_palindrome_slice_int(sv_pal, cmp_int, NULL) == true);
}

/* ── test_context_parameter ──────────────────────────────────────────────── */
static void test_context_parameter(void)
{
    /* With threshold=5: values 6,7,8,9 all compare equal; 1,2,3,4 compare equal
     * {6, 2, 7, 2, 8} — pairs: (6 over, 8 over)=equal, (2 not, 2 not)=equal → palindrome */
    int arr[] = {6, 2, 7, 2, 8};
    int threshold = 5;
    EXPECT(algo_is_palindrome(arr, 5, sizeof(int), cmp_int_threshold,
                              &threshold) == true);

    /* {6, 2, 7, 3, 8} — pairs: (6,8)=equal, (2 not, 3 not)=equal → palindrome */
    int arr2[] = {6, 2, 7, 3, 8};
    EXPECT(algo_is_palindrome(arr2, 5, sizeof(int), cmp_int_threshold,
                              &threshold) == true);

    /* {6, 2, 7, 8, 3} — pairs: (6 over, 3 not)=differ → not palindrome */
    int arr3[] = {6, 2, 7, 8, 3};
    EXPECT(algo_is_palindrome(arr3, 5, sizeof(int), cmp_int_threshold,
                              &threshold) == false);
}

/* ── test_dual_relationship ──────────────────────────────────────────────── */
static void test_dual_relationship(void)
{
    /* Property: is_palindrome(arr) == is_palindrome(reverse(arr))
     * Verify for a palindrome */
    int pal[] = {1, 2, 3, 2, 1};
    bool before = algo_is_palindrome(pal, 5, sizeof(int), cmp_int, NULL);
    algo_reverse(pal, 5, sizeof(int));
    bool after  = algo_is_palindrome(pal, 5, sizeof(int), cmp_int, NULL);
    EXPECT(before == true && after == true);

    /* Verify for a non-palindrome */
    int notpal[] = {1, 2, 3, 4, 5};
    before = algo_is_palindrome(notpal, 5, sizeof(int), cmp_int, NULL);
    algo_reverse(notpal, 5, sizeof(int));
    after  = algo_is_palindrome(notpal, 5, sizeof(int), cmp_int, NULL);
    EXPECT(before == false && after == false);
    /* And the reversal produced the expected result */
    EXPECT(notpal[0] == 5 && notpal[4] == 1);
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    Point arr[] = {{1, 10}, {2, 20}, {3, 30}, {4, 40}};
    slice_Point sv = slice_Point_from(arr, 4);

    algo_reverse_slice_Point(sv);
    EXPECT(arr[0].x == 4 && arr[1].x == 3 && arr[2].x == 2 && arr[3].x == 1);

    /* Reverse back — identity */
    algo_reverse_slice_Point(sv);
    EXPECT(arr[0].x == 1 && arr[3].x == 4);

    /* Palindrome by x: {1,2,1} → true */
    Point pal[] = {{1, 0}, {2, 0}, {1, 0}};
    slice_Point sv_pal = slice_Point_from(pal, 3);
    EXPECT(algo_is_palindrome_slice_Point(sv_pal, cmp_point_x, NULL) == true);

    /* {1,2,3} → false */
    Point notpal[] = {{1, 0}, {2, 0}, {3, 0}};
    slice_Point sv_notpal = slice_Point_from(notpal, 3);
    EXPECT(algo_is_palindrome_slice_Point(sv_notpal, cmp_point_x, NULL) == false);

    /* Empty */
    slice_Point empty = slice_Point_empty();
    algo_reverse_slice_Point(empty);
    EXPECT(algo_is_palindrome_slice_Point(empty, cmp_point_x, NULL) == true);
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)reverse_slice_suppress_unused;

    test_empty();
    test_single_element();
    test_even_length();
    test_odd_length();
    test_double_reverse_identity();
    test_palindrome_true();
    test_palindrome_false();
    test_palindrome_short_circuit();
    test_typed_macro();
    test_typed_slice();
    test_context_parameter();
    test_dual_relationship();
    test_point_struct();

    if (g_failed == 0) {
        printf("OK  reverse_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  reverse_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void reverse_fuzz_suppress_unused(void)
{
    (void)algo_reverse_slice_int;
    (void)algo_is_palindrome_slice_int;
    (void)algo_reverse_slice_Point;
    (void)algo_is_palindrome_slice_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz algo_reverse and algo_is_palindrome on raw byte input (treated as int[]).
 *
 * Invariants:
 *   1. Double-reverse restores original: reverse(reverse(arr)) == arr
 *   2. Palindrome status is invariant under reversal:
 *      is_palindrome(arr) == is_palindrome(reverse(arr))
 */

static int fuzz_cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    return *(const int*)a - *(const int*)b;
}

#define REVERSE_FUZZ_MAX 256

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)reverse_fuzz_suppress_unused;
    (void)reverse_slice_suppress_unused;

    if (size < sizeof(int)) return 0;

    usize n = size / sizeof(int);
    if (n > REVERSE_FUZZ_MAX) n = REVERSE_FUZZ_MAX;

    int original[REVERSE_FUZZ_MAX];
    int arr[REVERSE_FUZZ_MAX];
    memcpy(original, data, n * sizeof(int));
    memcpy(arr,      data, n * sizeof(int));

    /* Invariant 1: double-reverse is identity */
    algo_reverse(arr, n, sizeof(int));
    algo_reverse(arr, n, sizeof(int));

    for (usize i = 0; i < n; i++) {
        if (arr[i] != original[i]) __builtin_trap();
    }

    /* Invariant 2: palindrome status invariant under reversal */
    bool pal_before = algo_is_palindrome(original, n, sizeof(int),
                                         fuzz_cmp_int, NULL);

    /* Reverse once */
    algo_reverse(arr, n, sizeof(int));

    bool pal_after = algo_is_palindrome(arr, n, sizeof(int),
                                        fuzz_cmp_int, NULL);

    if (pal_before != pal_after) __builtin_trap();

    return 0;
}

#endif /* CANON_FUZZING */
