/**
 * @file search_test.c
 * @brief Tests for algo/search — binary search utilities for sorted sequences
 *
 * Five functions × three API levels:
 *   algo_lower_bound      / ALGO_LOWER_BOUND_TYPED      / algo_lower_bound_slice_##type
 *   algo_upper_bound      / ALGO_UPPER_BOUND_TYPED      / algo_upper_bound_slice_##type
 *   algo_find_sorted      / ALGO_FIND_SORTED_TYPED      / algo_find_sorted_slice_##type
 *   algo_binary_search    / ALGO_BINARY_SEARCH_TYPED    / algo_binary_search_slice_##type
 *   algo_equal_range      / ALGO_EQUAL_RANGE_TYPED      / algo_equal_range_slice_##type
 *
 * Two instantiations:
 *   int   — primary; all three levels exercised
 *   Point — struct coverage; slice level only
 *
 * Covers:
 *   - Empty array (len=0)           — each function's documented sentinel
 *   - Single element, key present   — exact match at index 0
 *   - Single element, key absent    — before/after cases
 *   - Key present once              — lower == upper - 1 == find_sorted
 *   - Key present multiple times    — lower/upper/equal_range all distinct
 *   - Key before all elements       — lower_bound == upper_bound == 0
 *   - Key after all elements        — lower_bound == upper_bound == len
 *   - Key between elements (absent) — lower_bound == upper_bound (empty range)
 *   - find_sorted: first match      — always returns lowest index of duplicates
 *   - binary_search consistency     — result == (find_sorted != CANON_USIZE_MAX)
 *   - equal_range invariant         — out[0] <= out[1], both in [0, len]
 *   - lower_bound <= upper_bound    — always
 *   - Typed macro level             — all five via ALGO_*_TYPED
 *   - Typed slice level             — all five via algo_*_slice_int
 *   - Point struct                  — algo_*_slice_Point
 *   - Context parameter             — comparator uses ctx pointer
 *   - CANON_USIZE_MAX sentinel      — find_sorted miss
 *
 * Fuzz entry point (CANON_FUZZING):
 *   Input bytes interpreted as int[]. Sorted in-place then searched with
 *   arbitrary keys derived from input. Invariants:
 *     1. lower_bound(arr, key) <= upper_bound(arr, key)
 *     2. binary_search(arr, key) == (find_sorted(arr, key) != CANON_USIZE_MAX)
 *     3. equal_range[0] == lower_bound(arr, key)
 *     4. equal_range[1] == upper_bound(arr, key)
 *     5. lower_bound and upper_bound results are always in [0, len]
 *     6. If binary_search is true, arr[lower_bound] == key (via cmp)
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/primitives/limits.h"
#include "core/primitives/compare.h"
#include "core/slice.h"
#include "algo/search/search.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice instantiations ──────────────────────────────────────────── */

DEFINE_SLICE(int)
DEFINE_ALGO_SEARCH(int)

typedef struct { int x; int y; } Point;
DEFINE_SLICE(Point)
DEFINE_ALGO_SEARCH(Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void search_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ════════════════════════════════════════════════════════════════════════════
   Unit test build
   ════════════════════════════════════════════════════════════════════════════ */

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Comparators ─────────────────────────────────────────────────────────── */

static int cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (va > vb) - (va < vb);
}

/* Reversed order comparator for context-parameter test */
static int cmp_int_desc(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (vb > va) - (vb < va);
}

/* Comparator that uses ctx as a scale factor */
static int cmp_int_scaled(const void* a, const void* b, void* ctx)
{
    int scale = *(const int*)ctx;
    int va = *(const int*)a * scale;
    int vb = *(const int*)b * scale;
    return (va > vb) - (va < vb);
}

static int cmp_point_x(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = ((const Point*)a)->x;
    int vb = ((const Point*)b)->x;
    return (va > vb) - (va < vb);
}

/* ── test_empty ──────────────────────────────────────────────────────────── */
static void test_empty(void)
{
    /* Use a valid non-NULL array pointer; len=0 controls the empty case */
    int dummy[1] = {0};
    int key = 5;
    usize range[2];

    EXPECT(algo_lower_bound(dummy, 0, sizeof(int), &key, cmp_int, NULL) == 0);
    EXPECT(algo_upper_bound(dummy, 0, sizeof(int), &key, cmp_int, NULL) == 0);
    EXPECT(algo_find_sorted(dummy, 0, sizeof(int), &key, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_binary_search(dummy, 0, sizeof(int), &key, cmp_int, NULL)
           == false);

    algo_equal_range(dummy, 0, sizeof(int), &key, cmp_int, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 0);

    /* Typed macro */
    EXPECT(ALGO_LOWER_BOUND_TYPED(dummy, 0, int, &key, cmp_int, NULL) == 0);
    EXPECT(ALGO_UPPER_BOUND_TYPED(dummy, 0, int, &key, cmp_int, NULL) == 0);
    EXPECT(ALGO_FIND_SORTED_TYPED(dummy, 0, int, &key, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(ALGO_BINARY_SEARCH_TYPED(dummy, 0, int, &key, cmp_int, NULL) == false);
    ALGO_EQUAL_RANGE_TYPED(dummy, 0, int, &key, cmp_int, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 0);

    /* Typed slice — empty */
    slice_int empty = slice_int_empty();
    EXPECT(algo_lower_bound_slice_int(empty, &key, cmp_int, NULL) == 0);
    EXPECT(algo_upper_bound_slice_int(empty, &key, cmp_int, NULL) == 0);
    EXPECT(algo_find_sorted_slice_int(empty, &key, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_binary_search_slice_int(empty, &key, cmp_int, NULL) == false);
    algo_equal_range_slice_int(empty, &key, cmp_int, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 0);
}

/* ── test_single_element ─────────────────────────────────────────────────── */
static void test_single_element(void)
{
    int arr[1] = {10};
    usize range[2];

    /* Key present */
    int key = 10;
    EXPECT(algo_lower_bound(arr, 1, sizeof(int), &key, cmp_int, NULL) == 0);
    EXPECT(algo_upper_bound(arr, 1, sizeof(int), &key, cmp_int, NULL) == 1);
    EXPECT(algo_find_sorted(arr, 1, sizeof(int), &key, cmp_int, NULL) == 0);
    EXPECT(algo_binary_search(arr, 1, sizeof(int), &key, cmp_int, NULL) == true);
    algo_equal_range(arr, 1, sizeof(int), &key, cmp_int, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 1);

    /* Key before the element */
    int before = 5;
    EXPECT(algo_lower_bound(arr, 1, sizeof(int), &before, cmp_int, NULL) == 0);
    EXPECT(algo_upper_bound(arr, 1, sizeof(int), &before, cmp_int, NULL) == 0);
    EXPECT(algo_find_sorted(arr, 1, sizeof(int), &before, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_binary_search(arr, 1, sizeof(int), &before, cmp_int, NULL) == false);
    algo_equal_range(arr, 1, sizeof(int), &before, cmp_int, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 0);

    /* Key after the element */
    int after = 20;
    EXPECT(algo_lower_bound(arr, 1, sizeof(int), &after, cmp_int, NULL) == 1);
    EXPECT(algo_upper_bound(arr, 1, sizeof(int), &after, cmp_int, NULL) == 1);
    EXPECT(algo_find_sorted(arr, 1, sizeof(int), &after, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_binary_search(arr, 1, sizeof(int), &after, cmp_int, NULL) == false);
    algo_equal_range(arr, 1, sizeof(int), &after, cmp_int, NULL, range);
    EXPECT(range[0] == 1 && range[1] == 1);
}

/* ── test_key_present_once ───────────────────────────────────────────────── */
static void test_key_present_once(void)
{
    /* {1, 3, 5, 7, 9} — all unique */
    int arr[] = {1, 3, 5, 7, 9};
    usize range[2];

    /* Search for 5 (index 2) */
    int key = 5;
    EXPECT(algo_lower_bound(arr, 5, sizeof(int), &key, cmp_int, NULL) == 2);
    EXPECT(algo_upper_bound(arr, 5, sizeof(int), &key, cmp_int, NULL) == 3);
    EXPECT(algo_find_sorted(arr, 5, sizeof(int), &key, cmp_int, NULL) == 2);
    EXPECT(algo_binary_search(arr, 5, sizeof(int), &key, cmp_int, NULL) == true);
    algo_equal_range(arr, 5, sizeof(int), &key, cmp_int, NULL, range);
    EXPECT(range[0] == 2 && range[1] == 3);

    /* Search for 1 (index 0 — first element) */
    int first = 1;
    EXPECT(algo_lower_bound(arr, 5, sizeof(int), &first, cmp_int, NULL) == 0);
    EXPECT(algo_upper_bound(arr, 5, sizeof(int), &first, cmp_int, NULL) == 1);
    EXPECT(algo_find_sorted(arr, 5, sizeof(int), &first, cmp_int, NULL) == 0);
    EXPECT(algo_binary_search(arr, 5, sizeof(int), &first, cmp_int, NULL) == true);

    /* Search for 9 (index 4 — last element) */
    int last = 9;
    EXPECT(algo_lower_bound(arr, 5, sizeof(int), &last, cmp_int, NULL) == 4);
    EXPECT(algo_upper_bound(arr, 5, sizeof(int), &last, cmp_int, NULL) == 5);
    EXPECT(algo_find_sorted(arr, 5, sizeof(int), &last, cmp_int, NULL) == 4);
    EXPECT(algo_binary_search(arr, 5, sizeof(int), &last, cmp_int, NULL) == true);
}

/* ── test_key_present_multiple ───────────────────────────────────────────── */
static void test_key_present_multiple(void)
{
    /* {1, 2, 2, 2, 5, 7, 9} — 2 appears at indices 1,2,3 */
    int arr[] = {1, 2, 2, 2, 5, 7, 9};
    usize n = 7;
    usize range[2];

    int key = 2;
    EXPECT(algo_lower_bound(arr, n, sizeof(int), &key, cmp_int, NULL) == 1);
    EXPECT(algo_upper_bound(arr, n, sizeof(int), &key, cmp_int, NULL) == 4);
    EXPECT(algo_find_sorted(arr, n, sizeof(int), &key, cmp_int, NULL) == 1);
    EXPECT(algo_binary_search(arr, n, sizeof(int), &key, cmp_int, NULL) == true);

    algo_equal_range(arr, n, sizeof(int), &key, cmp_int, NULL, range);
    EXPECT(range[0] == 1 && range[1] == 4);

    /* All same: {3, 3, 3, 3} */
    int same[] = {3, 3, 3, 3};
    int k = 3;
    EXPECT(algo_lower_bound(same, 4, sizeof(int), &k, cmp_int, NULL) == 0);
    EXPECT(algo_upper_bound(same, 4, sizeof(int), &k, cmp_int, NULL) == 4);
    EXPECT(algo_find_sorted(same, 4, sizeof(int), &k, cmp_int, NULL) == 0);
    EXPECT(algo_binary_search(same, 4, sizeof(int), &k, cmp_int, NULL) == true);

    algo_equal_range(same, 4, sizeof(int), &k, cmp_int, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 4);
}

/* ── test_key_absent ─────────────────────────────────────────────────────── */
static void test_key_absent(void)
{
    int arr[] = {1, 3, 5, 7, 9};
    usize n = 5;
    usize range[2];

    /* Before all elements */
    int before = 0;
    EXPECT(algo_lower_bound(arr, n, sizeof(int), &before, cmp_int, NULL) == 0);
    EXPECT(algo_upper_bound(arr, n, sizeof(int), &before, cmp_int, NULL) == 0);
    EXPECT(algo_find_sorted(arr, n, sizeof(int), &before, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_binary_search(arr, n, sizeof(int), &before, cmp_int, NULL) == false);
    algo_equal_range(arr, n, sizeof(int), &before, cmp_int, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 0);

    /* After all elements */
    int after = 10;
    EXPECT(algo_lower_bound(arr, n, sizeof(int), &after, cmp_int, NULL) == 5);
    EXPECT(algo_upper_bound(arr, n, sizeof(int), &after, cmp_int, NULL) == 5);
    EXPECT(algo_find_sorted(arr, n, sizeof(int), &after, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_binary_search(arr, n, sizeof(int), &after, cmp_int, NULL) == false);
    algo_equal_range(arr, n, sizeof(int), &after, cmp_int, NULL, range);
    EXPECT(range[0] == 5 && range[1] == 5);

    /* Between elements: 4 would go at index 2 (between 3 and 5) */
    int mid = 4;
    EXPECT(algo_lower_bound(arr, n, sizeof(int), &mid, cmp_int, NULL) == 2);
    EXPECT(algo_upper_bound(arr, n, sizeof(int), &mid, cmp_int, NULL) == 2);
    EXPECT(algo_find_sorted(arr, n, sizeof(int), &mid, cmp_int, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_binary_search(arr, n, sizeof(int), &mid, cmp_int, NULL) == false);
    algo_equal_range(arr, n, sizeof(int), &mid, cmp_int, NULL, range);
    EXPECT(range[0] == 2 && range[1] == 2);
}

/* ── test_typed_macro ────────────────────────────────────────────────────── */
static void test_typed_macro(void)
{
    int arr[] = {1, 2, 2, 2, 5, 7, 9};
    usize n = 7;
    usize range[2];
    int key = 2;

    EXPECT(ALGO_LOWER_BOUND_TYPED(arr, n, int, &key, cmp_int, NULL) == 1);
    EXPECT(ALGO_UPPER_BOUND_TYPED(arr, n, int, &key, cmp_int, NULL) == 4);
    EXPECT(ALGO_FIND_SORTED_TYPED(arr, n, int, &key, cmp_int, NULL) == 1);
    EXPECT(ALGO_BINARY_SEARCH_TYPED(arr, n, int, &key, cmp_int, NULL) == true);

    ALGO_EQUAL_RANGE_TYPED(arr, n, int, &key, cmp_int, NULL, range);
    EXPECT(range[0] == 1 && range[1] == 4);

    /* Absent key */
    int missing = 3;
    EXPECT(ALGO_LOWER_BOUND_TYPED(arr, n, int, &missing, cmp_int, NULL) == 4);
    EXPECT(ALGO_BINARY_SEARCH_TYPED(arr, n, int, &missing, cmp_int, NULL) == false);
    EXPECT(ALGO_FIND_SORTED_TYPED(arr, n, int, &missing, cmp_int, NULL)
           == CANON_USIZE_MAX);
}

/* ── test_typed_slice ────────────────────────────────────────────────────── */
static void test_typed_slice(void)
{
    int buf[] = {1, 2, 2, 2, 5, 7, 9};
    slice_int sv = slice_int_from(buf, 7);
    usize range[2];
    int key = 2;

    EXPECT(algo_lower_bound_slice_int(sv, &key, cmp_int, NULL) == 1);
    EXPECT(algo_upper_bound_slice_int(sv, &key, cmp_int, NULL) == 4);
    EXPECT(algo_find_sorted_slice_int(sv, &key, cmp_int, NULL) == 1);
    EXPECT(algo_binary_search_slice_int(sv, &key, cmp_int, NULL) == true);

    algo_equal_range_slice_int(sv, &key, cmp_int, NULL, range);
    EXPECT(range[0] == 1 && range[1] == 4);

    /* Absent key */
    int missing = 6;
    EXPECT(algo_lower_bound_slice_int(sv, &missing, cmp_int, NULL) == 5);
    EXPECT(algo_upper_bound_slice_int(sv, &missing, cmp_int, NULL) == 5);
    EXPECT(algo_binary_search_slice_int(sv, &missing, cmp_int, NULL) == false);

    algo_equal_range_slice_int(sv, &missing, cmp_int, NULL, range);
    EXPECT(range[0] == 5 && range[1] == 5);
}

/* ── test_lower_upper_bound_invariant ────────────────────────────────────── */
static void test_lower_upper_bound_invariant(void)
{
    /* lower_bound <= upper_bound for any key, always */
    int arr[] = {2, 4, 4, 6, 8, 8, 8, 10};
    usize n = 8;

    int keys[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
    for (usize i = 0; i < 11; i++) {
        usize lo = algo_lower_bound(arr, n, sizeof(int), &keys[i], cmp_int, NULL);
        usize hi = algo_upper_bound(arr, n, sizeof(int), &keys[i], cmp_int, NULL);
        EXPECT(lo <= hi);
        EXPECT(lo <= n && hi <= n);

        /* equal_range must match separate lower/upper calls */
        usize range[2];
        algo_equal_range(arr, n, sizeof(int), &keys[i], cmp_int, NULL, range);
        EXPECT(range[0] == lo && range[1] == hi);
    }
}

/* ── test_binary_search_consistency ─────────────────────────────────────── */
static void test_binary_search_consistency(void)
{
    int arr[] = {1, 2, 2, 4, 5, 5, 5, 9};
    usize n = 8;

    int keys[] = {0, 1, 2, 3, 4, 5, 6, 9, 10};
    for (usize i = 0; i < 9; i++) {
        bool found   = algo_binary_search(arr, n, sizeof(int), &keys[i],
                                          cmp_int, NULL);
        usize idx    = algo_find_sorted(arr, n, sizeof(int), &keys[i],
                                        cmp_int, NULL);
        bool by_find = (idx != CANON_USIZE_MAX);

        EXPECT(found == by_find);

        /* If found, arr[idx] must equal key */
        if (found) {
            EXPECT(cmp_int(&arr[idx], &keys[i], NULL) == 0);
        }
    }
}

/* ── test_context_parameter ──────────────────────────────────────────────── */
static void test_context_parameter(void)
{
    /* Descending array searched with descending comparator */
    int arr_desc[] = {9, 7, 5, 3, 1};
    int key = 5;

    EXPECT(algo_lower_bound(arr_desc, 5, sizeof(int), &key, cmp_int_desc, NULL)
           == 2);
    EXPECT(algo_upper_bound(arr_desc, 5, sizeof(int), &key, cmp_int_desc, NULL)
           == 3);
    EXPECT(algo_find_sorted(arr_desc, 5, sizeof(int), &key, cmp_int_desc, NULL)
           == 2);
    EXPECT(algo_binary_search(arr_desc, 5, sizeof(int), &key, cmp_int_desc, NULL)
           == true);

    /* Scale factor in ctx — scale=1 is identity */
    int arr[] = {1, 3, 5, 7, 9};
    int scale = 1;
    int k = 3;
    EXPECT(algo_lower_bound(arr, 5, sizeof(int), &k, cmp_int_scaled, &scale) == 1);
    EXPECT(algo_binary_search(arr, 5, sizeof(int), &k, cmp_int_scaled, &scale)
           == true);
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    /* Sorted by x */
    Point arr[] = {{1, 10}, {3, 30}, {3, 99}, {5, 50}, {7, 70}};
    slice_Point sv = slice_Point_from(arr, 5);
    usize range[2];

    /* Search for x=3 — two elements */
    Point key = {3, 0};
    EXPECT(algo_lower_bound_slice_Point(sv, &key, cmp_point_x, NULL) == 1);
    EXPECT(algo_upper_bound_slice_Point(sv, &key, cmp_point_x, NULL) == 3);
    EXPECT(algo_find_sorted_slice_Point(sv, &key, cmp_point_x, NULL) == 1);
    EXPECT(algo_binary_search_slice_Point(sv, &key, cmp_point_x, NULL) == true);

    algo_equal_range_slice_Point(sv, &key, cmp_point_x, NULL, range);
    EXPECT(range[0] == 1 && range[1] == 3);

    /* Search for x=4 — absent */
    Point missing = {4, 0};
    EXPECT(algo_binary_search_slice_Point(sv, &missing, cmp_point_x, NULL)
           == false);
    EXPECT(algo_find_sorted_slice_Point(sv, &missing, cmp_point_x, NULL)
           == CANON_USIZE_MAX);
    EXPECT(algo_lower_bound_slice_Point(sv, &missing, cmp_point_x, NULL) == 3);

    /* Empty Point slice */
    slice_Point empty = slice_Point_empty();
    EXPECT(algo_lower_bound_slice_Point(empty, &key, cmp_point_x, NULL) == 0);
    EXPECT(algo_binary_search_slice_Point(empty, &key, cmp_point_x, NULL) == false);
    algo_equal_range_slice_Point(empty, &key, cmp_point_x, NULL, range);
    EXPECT(range[0] == 0 && range[1] == 0);
}

/* ── Suppress Point search functions ─────────────────────────────────────── */
static void search_suppress_unused(void)
{
    /* All five Point slice search functions are exercised in test_point_struct.
     * Suppress the typed variants that are not called elsewhere. */
    (void)algo_lower_bound_slice_Point;
    (void)algo_upper_bound_slice_Point;
    (void)algo_find_sorted_slice_Point;
    (void)algo_binary_search_slice_Point;
    (void)algo_equal_range_slice_Point;
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)search_slice_suppress_unused;
    (void)search_suppress_unused;

    test_empty();
    test_single_element();
    test_key_present_once();
    test_key_present_multiple();
    test_key_absent();
    test_typed_macro();
    test_typed_slice();
    test_lower_upper_bound_invariant();
    test_binary_search_consistency();
    test_context_parameter();
    test_point_struct();

    if (g_failed == 0) {
        printf("OK  search_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  search_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void search_fuzz_suppress_unused(void)
{
    (void)algo_lower_bound_slice_int;
    (void)algo_upper_bound_slice_int;
    (void)algo_find_sorted_slice_int;
    (void)algo_binary_search_slice_int;
    (void)algo_equal_range_slice_int;
    (void)algo_lower_bound_slice_Point;
    (void)algo_upper_bound_slice_Point;
    (void)algo_find_sorted_slice_Point;
    (void)algo_binary_search_slice_Point;
    (void)algo_equal_range_slice_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz all five search functions on sorted int arrays.
 *
 * Strategy:
 *   - Interpret the first half of input as array data (sorted in-place).
 *   - Interpret one int from the second half as the search key.
 *   - Run all five functions and check structural invariants.
 *
 * Invariants (do NOT depend on sorted order of original data):
 *   1. lower_bound(arr, key) <= upper_bound(arr, key)
 *   2. Both lower and upper are in [0, n]
 *   3. binary_search == (find_sorted != CANON_USIZE_MAX)
 *   4. equal_range[0] == lower_bound, equal_range[1] == upper_bound
 *   5. If binary_search is true:
 *      a. lower_bound index is in [0, n)
 *      b. arr[lower_bound] == key (via cmp)
 *      c. find_sorted index is in [0, n)
 *      d. arr[find_sorted] == key (via cmp)
 */

static int fuzz_cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (va > vb) - (va < vb);
}

/* Simple insertion sort for small fuzz arrays */
static void isort(int* arr, usize n)
{
    for (usize i = 1; i < n; i++) {
        int tmp = arr[i];
        usize j = i;
        while (j > 0 && arr[j - 1] > tmp) {
            arr[j] = arr[j - 1];
            j--;
        }
        arr[j] = tmp;
    }
}

#define SEARCH_FUZZ_MAX 128

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)search_fuzz_suppress_unused;
    (void)search_slice_suppress_unused;

    /* Need at least 2 ints: one element + one key */
    if (size < 2 * sizeof(int)) return 0;

    usize n = (size / sizeof(int)) - 1;
    if (n > SEARCH_FUZZ_MAX) n = SEARCH_FUZZ_MAX;

    int arr[SEARCH_FUZZ_MAX];
    int key;

    memcpy(arr, data, n * sizeof(int));
    memcpy(&key, data + n * sizeof(int), sizeof(int));

    /* Sort so the precondition is satisfied */
    isort(arr, n);

    usize lo    = algo_lower_bound(arr, n, sizeof(int), &key, fuzz_cmp_int, NULL);
    usize hi    = algo_upper_bound(arr, n, sizeof(int), &key, fuzz_cmp_int, NULL);
    usize idx   = algo_find_sorted(arr, n, sizeof(int), &key, fuzz_cmp_int, NULL);
    bool  found = algo_binary_search(arr, n, sizeof(int), &key, fuzz_cmp_int, NULL);
    usize range[2];
    algo_equal_range(arr, n, sizeof(int), &key, fuzz_cmp_int, NULL, range);

    /* Invariant 1: lo <= hi */
    if (lo > hi) __builtin_trap();

    /* Invariant 2: both in [0, n] */
    if (lo > n || hi > n) __builtin_trap();

    /* Invariant 3: binary_search == (find_sorted != CANON_USIZE_MAX) */
    if (found != (idx != CANON_USIZE_MAX)) __builtin_trap();

    /* Invariant 4: equal_range matches separate calls */
    if (range[0] != lo || range[1] != hi) __builtin_trap();

    /* Invariant 5: if found, verify match */
    if (found) {
        if (lo >= n) __builtin_trap();
        if (fuzz_cmp_int(&arr[lo], &key, NULL) != 0) __builtin_trap();
        if (idx >= n) __builtin_trap();
        if (fuzz_cmp_int(&arr[idx], &key, NULL) != 0) __builtin_trap();
    }

    return 0;
}

#endif /* CANON_FUZZING */
