/**
 * @file sort_test.c
 * @brief Tests for algo/sort — stable hybrid insertion/merge sort
 *
 * Two functions, three API levels each:
 *   algo_sort        / ALGO_SORT_TYPED        / algo_sort_slice_##type
 *   algo_is_sorted   / ALGO_IS_SORTED_TYPED   / algo_is_sorted_slice_##type
 *
 * Two instantiations:
 *   int   — primary; all three levels exercised
 *   Point — struct coverage; slice level only
 *
 * Covers:
 *   - Empty (len=0)            — sort: no-op; is_sorted: true
 *   - Single element (len=1)   — sort: no-op; is_sorted: true
 *   - Two elements             — exercises simple swap case
 *   - Small (len < 16)         — insertion sort path
 *   - Large (len >= 16)        — merge sort path (with temp)
 *   - Large, no temp           — insertion sort fallback (NULL temp)
 *   - Already sorted           — is_sorted true; sort is idempotent
 *   - Reverse sorted           — worst case for insertion sort
 *   - All same values          — stable; is_sorted true
 *   - Stability                — equal elements preserve original relative order
 *   - Double sort idempotent   — sort(sort(x)) == sort(x)
 *   - Permutation preservation — same elements before and after sort
 *   - algo_is_sorted false     — first/last/middle pair out of order
 *   - Typed macro              — ALGO_SORT_TYPED / ALGO_IS_SORTED_TYPED
 *   - Typed slice              — algo_sort_slice_int / algo_is_sorted_slice_int
 *   - Point struct             — algo_sort_slice_Point / algo_is_sorted_slice_Point
 *   - Context parameter        — comparator uses ctx for custom ordering
 *
 * Fuzz entry point (CANON_FUZZING):
 *   Input bytes as int[]. Tests:
 *     1. is_sorted after sort (with and without temp)
 *     2. Sort twice = sort once (idempotent)
 *     3. Sum preserved (permutation, no elements lost/added)
 *     4. Merge sort and insertion sort produce the same result
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/primitives/compare.h"
#include "core/slice.h"
#include "algo/sort/sort.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice instantiations ──────────────────────────────────────────── */

DEFINE_SLICE(int)
DEFINE_ALGO_SORT(int)

typedef struct { int key; int seq; } Point; /* seq = original index for stability */
DEFINE_SLICE(Point)
DEFINE_ALGO_SORT(Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void sort_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ════════════════════════════════════════════════════════════════════════════
   Unit test build
   ════════════════════════════════════════════════════════════════════════════ */

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Comparators ─────────────────────────────────────────────────────────── */

static int cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (va > vb) - (va < vb);
}

static int cmp_int_desc(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (vb > va) - (vb < va);
}

/* For stability test: sort only by .key, ignore .seq */
static int cmp_point_key(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = ((const Point*)a)->key;
    int vb = ((const Point*)b)->key;
    return (va > vb) - (va < vb);
}

/* ── helper: check array is sorted ──────────────────────────────────────── */
static bool is_sorted_int(const int* arr, usize n)
{
    for (usize i = 1; i < n; i++) {
        if (arr[i] < arr[i - 1]) return false;
    }
    return true;
}

/* ── helper: sum of elements (permutation check) ─────────────────────────── */
static long long sum_int(const int* arr, usize n)
{
    long long s = 0;
    for (usize i = 0; i < n; i++) s += arr[i];
    return s;
}

/* ── test_empty ──────────────────────────────────────────────────────────── */
static void test_empty(void)
{
    int dummy[1] = {42};
    int tmp[1]   = {0};

    algo_sort(dummy, 0, sizeof(int), cmp_int, NULL, tmp);
    EXPECT(dummy[0] == 42);

    EXPECT(algo_is_sorted(dummy, 0, sizeof(int), cmp_int, NULL) == true);

    ALGO_SORT_TYPED(dummy, 0, int, cmp_int, NULL);
    EXPECT(dummy[0] == 42);
    EXPECT(ALGO_IS_SORTED_TYPED(dummy, 0, int, cmp_int, NULL) == true);

    slice_int empty = slice_int_empty();
    algo_sort_slice_int(empty, cmp_int, NULL, NULL, 0);
    EXPECT(algo_is_sorted_slice_int(empty, cmp_int, NULL) == true);
}

/* ── test_single_element ─────────────────────────────────────────────────── */
static void test_single_element(void)
{
    int arr[1] = {99};
    int tmp[1] = {0};

    algo_sort(arr, 1, sizeof(int), cmp_int, NULL, tmp);
    EXPECT(arr[0] == 99);

    EXPECT(algo_is_sorted(arr, 1, sizeof(int), cmp_int, NULL) == true);

    slice_int sv = slice_int_from(arr, 1);
    algo_sort_slice_int(sv, cmp_int, NULL, tmp, 1);
    EXPECT(arr[0] == 99);
    EXPECT(algo_is_sorted_slice_int(sv, cmp_int, NULL) == true);
}

/* ── test_two_elements ───────────────────────────────────────────────────── */
static void test_two_elements(void)
{
    int arr[] = {5, 1};
    int tmp[2];

    algo_sort(arr, 2, sizeof(int), cmp_int, NULL, tmp);
    EXPECT(arr[0] == 1 && arr[1] == 5);
    EXPECT(algo_is_sorted(arr, 2, sizeof(int), cmp_int, NULL) == true);

    /* Already sorted */
    algo_sort(arr, 2, sizeof(int), cmp_int, NULL, tmp);
    EXPECT(arr[0] == 1 && arr[1] == 5);
}

/* ── test_small_insertion_path ───────────────────────────────────────────── */
static void test_small_insertion_path(void)
{
    /* len=7 → insertion sort path (< 16) */
    int arr[] = {64, 34, 25, 12, 22, 11, 90};
    long long before = sum_int(arr, 7);

    algo_sort(arr, 7, sizeof(int), cmp_int, NULL, NULL);

    EXPECT(arr[0] == 11 && arr[1] == 12 && arr[2] == 22 && arr[3] == 25 &&
           arr[4] == 34 && arr[5] == 64 && arr[6] == 90);
    EXPECT(algo_is_sorted(arr, 7, sizeof(int), cmp_int, NULL) == true);
    EXPECT(sum_int(arr, 7) == before);
}

/* ── test_large_merge_path ───────────────────────────────────────────────── */
static void test_large_merge_path(void)
{
    /* len=20 → merge sort path (>= 16, with temp) */
    int arr[] = {15,3,9,7,1,14,20,8,6,17,2,18,10,5,13,4,16,11,19,12};
    int tmp[20];
    long long before = sum_int(arr, 20);

    algo_sort(arr, 20, sizeof(int), cmp_int, NULL, tmp);

    EXPECT(is_sorted_int(arr, 20));
    EXPECT(sum_int(arr, 20) == before);
    /* Spot check */
    EXPECT(arr[0] == 1 && arr[9] == 10 && arr[19] == 20);
}

/* ── test_large_no_temp_fallback ─────────────────────────────────────────── */
static void test_large_no_temp_fallback(void)
{
    /* len=20, NULL temp → insertion sort fallback (O(n²)) */
    int arr[] = {15,3,9,7,1,14,20,8,6,17,2,18,10,5,13,4,16,11,19,12};
    long long before = sum_int(arr, 20);

    algo_sort(arr, 20, sizeof(int), cmp_int, NULL, NULL);

    EXPECT(is_sorted_int(arr, 20));
    EXPECT(sum_int(arr, 20) == before);
}

/* ── test_reverse_sorted ─────────────────────────────────────────────────── */
static void test_reverse_sorted(void)
{
    int arr[] = {20, 18, 16, 14, 12, 10, 8, 6, 4, 2,
                 19, 17, 15, 13, 11,  9, 7, 5, 3, 1};
    int tmp[20];
    long long before = sum_int(arr, 20);

    algo_sort(arr, 20, sizeof(int), cmp_int, NULL, tmp);

    EXPECT(is_sorted_int(arr, 20));
    EXPECT(sum_int(arr, 20) == before);
    EXPECT(arr[0] == 1 && arr[19] == 20);
}

/* ── test_all_same ───────────────────────────────────────────────────────── */
static void test_all_same(void)
{
    int arr[] = {7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
                 7, 7, 7, 7, 7, 7, 7, 7, 7, 7};
    int tmp[20];

    algo_sort(arr, 20, sizeof(int), cmp_int, NULL, tmp);

    EXPECT(is_sorted_int(arr, 20));
    for (int i = 0; i < 20; i++) {
        EXPECT(arr[i] == 7);
    }
}

/* ── test_stability ──────────────────────────────────────────────────────── */
static void test_stability(void)
{
    /* Points with duplicate keys — sort by key only.
     * Stability: elements with the same key must preserve relative seq order. */
    Point arr[] = {
        {3, 0}, {1, 1}, {2, 2}, {1, 3}, {3, 4},
        {2, 5}, {1, 6}, {2, 7}, {3, 8}, {1, 9},
        {3,10}, {2,11}, {1,12}, {2,13}, {3,14},
        {1,15}, {2,16}, {3,17}, {1,18}, {2,19},
    };
    Point tmp[20];
    slice_Point sv = slice_Point_from(arr, 20);

    algo_sort_slice_Point(sv, cmp_point_key, NULL, tmp, 20);

    /* All key=1 elements come first, then key=2, then key=3 */
    for (usize i = 0; i < 20; i++) {
        if (i < 7)       EXPECT(arr[i].key == 1);
        else if (i < 14) EXPECT(arr[i].key == 2);
        else             EXPECT(arr[i].key == 3);
    }

    /* Within each group, seq must be strictly increasing (stability) */
    for (usize i = 1; i < 20; i++) {
        if (arr[i].key == arr[i-1].key) {
            EXPECT(arr[i].seq > arr[i-1].seq);
        }
    }

    EXPECT(algo_is_sorted_slice_Point(sv, cmp_point_key, NULL) == true);
}

/* ── test_double_sort_idempotent ─────────────────────────────────────────── */
static void test_double_sort_idempotent(void)
{
    int arr[] = {5, 2, 8, 1, 9, 3, 7, 4, 6, 0,
                 15,12,18,11,19,13,17,14,16,10};
    int tmp[20];

    algo_sort(arr, 20, sizeof(int), cmp_int, NULL, tmp);
    int snap[20];
    memcpy(snap, arr, 20 * sizeof(int));

    /* Sort again — must produce identical result */
    algo_sort(arr, 20, sizeof(int), cmp_int, NULL, tmp);
    for (int i = 0; i < 20; i++) {
        EXPECT(arr[i] == snap[i]);
    }
}

/* ── test_is_sorted_false ────────────────────────────────────────────────── */
static void test_is_sorted_false(void)
{
    /* Unsorted at start */
    int arr1[] = {2, 1, 3, 4, 5};
    EXPECT(algo_is_sorted(arr1, 5, sizeof(int), cmp_int, NULL) == false);

    /* Unsorted only at end */
    int arr2[] = {1, 2, 3, 5, 4};
    EXPECT(algo_is_sorted(arr2, 5, sizeof(int), cmp_int, NULL) == false);

    /* Unsorted in the middle */
    int arr3[] = {1, 2, 5, 3, 4};
    EXPECT(algo_is_sorted(arr3, 5, sizeof(int), cmp_int, NULL) == false);
}

/* ── test_typed_macro ────────────────────────────────────────────────────── */
static void test_typed_macro(void)
{
    int arr[] = {5, 1, 4, 2, 3, 9, 7, 8, 6, 0,
                 15,11,14,12,13,19,17,18,16,10};

    EXPECT(ALGO_IS_SORTED_TYPED(arr, 20, int, cmp_int, NULL) == false);
    ALGO_SORT_TYPED(arr, 20, int, cmp_int, NULL);
    EXPECT(ALGO_IS_SORTED_TYPED(arr, 20, int, cmp_int, NULL) == true);
    EXPECT(arr[0] == 0 && arr[19] == 19);

    /* Descending comparator */
    int arr2[] = {1, 2, 3, 4, 5};
    ALGO_SORT_TYPED(arr2, 5, int, cmp_int_desc, NULL);
    EXPECT(arr2[0] == 5 && arr2[4] == 1);
    EXPECT(ALGO_IS_SORTED_TYPED(arr2, 5, int, cmp_int_desc, NULL) == true);
    EXPECT(ALGO_IS_SORTED_TYPED(arr2, 5, int, cmp_int, NULL) == false);
}

/* ── test_typed_slice ────────────────────────────────────────────────────── */
static void test_typed_slice(void)
{
    int buf[] = {7, 2, 9, 4, 1, 8, 5, 3, 6, 0,
                 17,12,19,14,11,18,15,13,16,10};
    int tmp[20];
    slice_int sv = slice_int_from(buf, 20);

    EXPECT(algo_is_sorted_slice_int(sv, cmp_int, NULL) == false);

    algo_sort_slice_int(sv, cmp_int, NULL, tmp, 20);

    EXPECT(algo_is_sorted_slice_int(sv, cmp_int, NULL) == true);
    EXPECT(buf[0] == 0 && buf[19] == 19);

    /* No temp — insertion sort fallback */
    int buf2[] = {9, 7, 5, 3, 1, 8, 6, 4, 2, 0,
                  19,17,15,13,11,18,16,14,12,10};
    slice_int sv2 = slice_int_from(buf2, 20);
    algo_sort_slice_int(sv2, cmp_int, NULL, NULL, 0);
    EXPECT(algo_is_sorted_slice_int(sv2, cmp_int, NULL) == true);
}

/* ── test_context_parameter ──────────────────────────────────────────────── */
static void test_context_parameter(void)
{
    /* Sort in descending order using cmp_int_desc */
    int arr[] = {3, 1, 4, 1, 5, 9, 2, 6, 5, 3,
                 5, 8, 9, 7, 9, 3, 2, 3, 8, 4};
    int tmp[20];

    algo_sort(arr, 20, sizeof(int), cmp_int_desc, NULL, tmp);

    /* Verify descending order */
    for (int i = 1; i < 20; i++) {
        EXPECT(arr[i] <= arr[i-1]);
    }

    EXPECT(algo_is_sorted(arr, 20, sizeof(int), cmp_int_desc, NULL) == true);
    EXPECT(algo_is_sorted(arr, 20, sizeof(int), cmp_int, NULL) == false);
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    Point arr[] = {
        {5,0},{1,1},{3,2},{2,3},{4,4},
        {15,5},{11,6},{13,7},{12,8},{14,9},
        {9,10},{6,11},{8,12},{7,13},{10,14},
        {20,15},{16,16},{18,17},{17,18},{19,19},
    };
    Point tmp[20];
    slice_Point sv = slice_Point_from(arr, 20);

    EXPECT(algo_is_sorted_slice_Point(sv, cmp_point_key, NULL) == false);

    algo_sort_slice_Point(sv, cmp_point_key, NULL, tmp, 20);

    EXPECT(algo_is_sorted_slice_Point(sv, cmp_point_key, NULL) == true);
    EXPECT(arr[0].key == 1 && arr[19].key == 20);

    /* Empty Point slice */
    slice_Point empty = slice_Point_empty();
    algo_sort_slice_Point(empty, cmp_point_key, NULL, NULL, 0);
    EXPECT(algo_is_sorted_slice_Point(empty, cmp_point_key, NULL) == true);
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)sort_slice_suppress_unused;

    test_empty();
    test_single_element();
    test_two_elements();
    test_small_insertion_path();
    test_large_merge_path();
    test_large_no_temp_fallback();
    test_reverse_sorted();
    test_all_same();
    test_stability();
    test_double_sort_idempotent();
    test_is_sorted_false();
    test_typed_macro();
    test_typed_slice();
    test_context_parameter();
    test_point_struct();

    if (g_failed == 0) {
        printf("OK  sort_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  sort_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void sort_fuzz_suppress_unused(void)
{
    (void)algo_sort_slice_int;
    (void)algo_is_sorted_slice_int;
    (void)algo_sort_slice_Point;
    (void)algo_is_sorted_slice_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz algo_sort on int arrays. Invariants:
 *   1. is_sorted after sort (merge path, with temp)
 *   2. is_sorted after sort (insertion path, NULL temp)
 *   3. Sort twice is idempotent (sort(sort(x)) == sort(x))
 *   4. Merge sort and insertion sort produce the same result
 *   5. Sum of elements is unchanged (permutation — nothing added/lost)
 */

#define SORT_FUZZ_MAX 256

static int fuzz_cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (va > vb) - (va < vb);
}

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)sort_fuzz_suppress_unused;
    (void)sort_slice_suppress_unused;

    if (size < sizeof(int)) return 0;

    usize n = size / sizeof(int);
    if (n > SORT_FUZZ_MAX) n = SORT_FUZZ_MAX;

    int orig[SORT_FUZZ_MAX];
    int arr_merge[SORT_FUZZ_MAX];
    int arr_insert[SORT_FUZZ_MAX];
    int arr_twice[SORT_FUZZ_MAX];
    int tmp[SORT_FUZZ_MAX];

    memcpy(orig,       data, n * sizeof(int));
    memcpy(arr_merge,  data, n * sizeof(int));
    memcpy(arr_insert, data, n * sizeof(int));
    memcpy(arr_twice,  data, n * sizeof(int));

    /* Compute sum before */
    long long sum_before = 0;
    for (usize i = 0; i < n; i++) sum_before += orig[i];

    /* Invariant 1: sort with temp (merge path) produces sorted output */
    algo_sort(arr_merge, n, sizeof(int), fuzz_cmp_int, NULL, tmp);
    if (!algo_is_sorted(arr_merge, n, sizeof(int), fuzz_cmp_int, NULL))
        __builtin_trap();

    /* Invariant 2: sort without temp (insertion path) produces sorted output */
    algo_sort(arr_insert, n, sizeof(int), fuzz_cmp_int, NULL, NULL);
    if (!algo_is_sorted(arr_insert, n, sizeof(int), fuzz_cmp_int, NULL))
        __builtin_trap();

    /* Invariant 4: both paths produce the same result */
    for (usize i = 0; i < n; i++) {
        if (arr_merge[i] != arr_insert[i]) __builtin_trap();
    }

    /* Invariant 3: sort twice is idempotent */
    algo_sort(arr_twice, n, sizeof(int), fuzz_cmp_int, NULL, tmp);
    algo_sort(arr_twice, n, sizeof(int), fuzz_cmp_int, NULL, tmp);
    for (usize i = 0; i < n; i++) {
        if (arr_twice[i] != arr_merge[i]) __builtin_trap();
    }

    /* Invariant 5: sum preserved */
    long long sum_after = 0;
    for (usize i = 0; i < n; i++) sum_after += arr_merge[i];
    if (sum_before != sum_after) __builtin_trap();

    return 0;
}

#endif /* CANON_FUZZING */
