/**
 * @file unique_test.c
 * @brief Tests for algo/unique — consecutive duplicate removal
 *
 * One function, three API levels:
 *   algo_unique          — generic (void* interface)
 *   ALGO_UNIQUE_TYPED    — typed macro, compile-time sizeof
 *   algo_unique_slice_##type — typed slice
 *
 * Two instantiations:
 *   int   — primary; all three levels exercised
 *   Point — struct coverage; slice level only
 *
 * Covers:
 *   - Empty (len=0)                    — returns 0, no-op
 *   - Single element                   — returns 1, no-op
 *   - All same values                  — returns 1, single element kept
 *   - No duplicates                    — returns len, nothing moved
 *   - All consecutive duplicates       — pairs reduced to one each
 *   - Run of more than 2 equal values  — entire run collapsed to one
 *   - Mixed runs and unique elements   — correct interleaving
 *   - First and last are equal pairs   — boundary cases
 *   - Two elements equal               — returns 1
 *   - Two elements different           — returns 2
 *   - Consecutive-only (not global)    — non-adjacent duplicates survive
 *   - Sort-then-unique = full dedup    — canonical pattern verified
 *   - Return value accuracy            — n is correct for all cases
 *   - Stale data beyond n              — not read (verified by count)
 *   - Typed macro                      — ALGO_UNIQUE_TYPED
 *   - Typed slice                      — algo_unique_slice_int
 *   - Point struct                     — algo_unique_slice_Point
 *   - Context parameter                — comparator uses ctx
 *   - Idempotency                      — unique(unique(x)) == unique(x)
 *
 * Fuzz entry point (CANON_FUZZING):
 *   Input bytes as int[]. Invariants:
 *     1. Return value n is in [1, len] for non-empty input
 *     2. arr[0..n-1] has no consecutive equal pairs after unique
 *     3. Idempotent: applying unique a second time returns same n
 *     4. n <= len (unique never grows the array)
 *     5. First element is always preserved: arr[0] unchanged
 *     6. Sort-then-unique: n from unique(sort(x)) equals number of
 *        distinct values in x (verified by re-counting)
 */

#define CANON_CONTRACT_IMPL

#include "core/primitives/types.h"
#include "core/primitives/compare.h"
#include "core/slice.h"
#include "algo/unique/unique.h"
#include "algo/sort/sort.h"

#include <stdio.h>
#include <string.h>

/* ── Typed slice instantiations ──────────────────────────────────────────── */

DEFINE_SLICE(int)
DEFINE_ALGO_UNIQUE(int)

typedef struct { int key; int val; } Point;
DEFINE_SLICE(Point)
DEFINE_ALGO_UNIQUE(Point)

/* ── Suppress unused slice functions generated by DEFINE_SLICE ───────────── */
static void unique_slice_suppress_unused(void)
{
    /* int slice */
    (void)slice_int_len;
    (void)slice_int_is_empty;
    (void)slice_int_get;
    (void)slice_int_get_unchecked;
    (void)slice_int_at;
    (void)slice_int_first;
    (void)slice_int_last;
    (void)slice_int_take;
    (void)slice_int_skip;
    (void)slice_int_as_bytes;
    (void)slice_int_as_cbytes;

    /* Point slice */
    (void)slice_Point_len;
    (void)slice_Point_is_empty;
    (void)slice_Point_get;
    (void)slice_Point_get_unchecked;
    (void)slice_Point_at;
    (void)slice_Point_first;
    (void)slice_Point_last;
    (void)slice_Point_take;
    (void)slice_Point_skip;
    (void)slice_Point_as_bytes;
    (void)slice_Point_as_cbytes;
}

/* ════════════════════════════════════════════════════════════════════════════
   Unit test build
   ════════════════════════════════════════════════════════════════════════════ */

#ifndef CANON_FUZZING

static int g_failed = 0;

#define EXPECT(cond)                                                  \
    do {                                                              \
        if (!(cond)) {                                                \
            fprintf(stderr, "FAIL %s:%d  %s\n",                      \
                    __FILE__, __LINE__, #cond);                       \
            g_failed++;                                               \
        }                                                             \
    } while (0)

/* ── Comparators ─────────────────────────────────────────────────────────── */

static int cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (va > vb) - (va < vb);
}

/* Equality only — treats values as equal when their difference is < threshold */
static int cmp_int_near(const void* a, const void* b, void* ctx)
{
    int thr = *(const int*)ctx;
    int d   = *(const int*)a - *(const int*)b;
    if (d < 0) d = -d;
    return (d >= thr) ? 1 : 0;
}

static int cmp_point_key(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = ((const Point*)a)->key;
    int vb = ((const Point*)b)->key;
    return (va > vb) - (va < vb);
}

/* ── helper: verify no consecutive equal pair in arr[0..n-1] ─────────────── */
static bool has_no_consecutive_dups(const int* arr, usize n)
{
    for (usize i = 1; i < n; i++) {
        if (arr[i] == arr[i-1]) return false;
    }
    return true;
}

/* ── test_empty ──────────────────────────────────────────────────────────── */
static void test_empty(void)
{
    int dummy[1] = {42};

    usize n = algo_unique(dummy, 0, sizeof(int), cmp_int, NULL);
    EXPECT(n == 0);
    EXPECT(dummy[0] == 42); /* untouched */

    n = ALGO_UNIQUE_TYPED(dummy, 0, int, cmp_int, NULL);
    EXPECT(n == 0);

    slice_int empty = slice_int_empty();
    n = algo_unique_slice_int(empty, cmp_int, NULL);
    EXPECT(n == 0);
}

/* ── test_single_element ─────────────────────────────────────────────────── */
static void test_single_element(void)
{
    int arr[1] = {7};

    usize n = algo_unique(arr, 1, sizeof(int), cmp_int, NULL);
    EXPECT(n == 1);
    EXPECT(arr[0] == 7);

    slice_int sv = slice_int_from(arr, 1);
    n = algo_unique_slice_int(sv, cmp_int, NULL);
    EXPECT(n == 1);
    EXPECT(arr[0] == 7);
}

/* ── test_all_same ───────────────────────────────────────────────────────── */
static void test_all_same(void)
{
    int arr[] = {5, 5, 5, 5, 5};

    usize n = algo_unique(arr, 5, sizeof(int), cmp_int, NULL);
    EXPECT(n == 1);
    EXPECT(arr[0] == 5);
}

/* ── test_no_duplicates ──────────────────────────────────────────────────── */
static void test_no_duplicates(void)
{
    int arr[] = {1, 2, 3, 4, 5};
    int copy[5];
    memcpy(copy, arr, sizeof(arr));

    usize n = algo_unique(arr, 5, sizeof(int), cmp_int, NULL);
    EXPECT(n == 5);
    for (int i = 0; i < 5; i++) {
        EXPECT(arr[i] == copy[i]); /* nothing moved */
    }
}

/* ── test_basic_dedup ────────────────────────────────────────────────────── */
static void test_basic_dedup(void)
{
    /* Standard pairs */
    int arr[] = {1, 1, 2, 2, 3};
    usize n = algo_unique(arr, 5, sizeof(int), cmp_int, NULL);
    EXPECT(n == 3);
    EXPECT(arr[0] == 1 && arr[1] == 2 && arr[2] == 3);

    /* Two equal elements */
    int arr2[] = {7, 7};
    n = algo_unique(arr2, 2, sizeof(int), cmp_int, NULL);
    EXPECT(n == 1);
    EXPECT(arr2[0] == 7);

    /* Two different elements */
    int arr3[] = {3, 4};
    n = algo_unique(arr3, 2, sizeof(int), cmp_int, NULL);
    EXPECT(n == 2);
    EXPECT(arr3[0] == 3 && arr3[1] == 4);
}

/* ── test_long_run ───────────────────────────────────────────────────────── */
static void test_long_run(void)
{
    /* Run of 5 same values */
    int arr[] = {9, 9, 9, 9, 9, 1, 2};
    usize n = algo_unique(arr, 7, sizeof(int), cmp_int, NULL);
    EXPECT(n == 3);
    EXPECT(arr[0] == 9 && arr[1] == 1 && arr[2] == 2);

    /* Single run in the middle */
    int arr2[] = {1, 2, 3, 3, 3, 4, 5};
    n = algo_unique(arr2, 7, sizeof(int), cmp_int, NULL);
    EXPECT(n == 5);
    EXPECT(arr2[0] == 1 && arr2[1] == 2 && arr2[2] == 3 &&
           arr2[3] == 4 && arr2[4] == 5);
}

/* ── test_boundary_duplicates ────────────────────────────────────────────── */
static void test_boundary_duplicates(void)
{
    /* Duplicate at start */
    int arr[] = {1, 1, 2, 3, 4};
    usize n = algo_unique(arr, 5, sizeof(int), cmp_int, NULL);
    EXPECT(n == 4);
    EXPECT(arr[0] == 1 && arr[3] == 4);

    /* Duplicate at end */
    int arr2[] = {1, 2, 3, 4, 4};
    n = algo_unique(arr2, 5, sizeof(int), cmp_int, NULL);
    EXPECT(n == 4);
    EXPECT(arr2[0] == 1 && arr2[3] == 4);

    /* Both ends duplicated */
    int arr3[] = {2, 2, 3, 4, 4};
    n = algo_unique(arr3, 5, sizeof(int), cmp_int, NULL);
    EXPECT(n == 3);
    EXPECT(arr3[0] == 2 && arr3[1] == 3 && arr3[2] == 4);
}

/* ── test_consecutive_only ───────────────────────────────────────────────── */
static void test_consecutive_only(void)
{
    /* Non-adjacent duplicates are NOT removed */
    int arr[] = {3, 1, 2, 1, 2, 3};
    usize n = algo_unique(arr, 6, sizeof(int), cmp_int, NULL);
    EXPECT(n == 6); /* nothing removed — no consecutive equal pairs */
    EXPECT(arr[0] == 3 && arr[5] == 3);

    /* Only adjacent 1,1 is removed, the non-adjacent 3s survive */
    int arr2[] = {3, 1, 1, 2, 3};
    n = algo_unique(arr2, 5, sizeof(int), cmp_int, NULL);
    EXPECT(n == 4);
    EXPECT(arr2[0] == 3 && arr2[1] == 1 && arr2[2] == 2 && arr2[3] == 3);
}

/* ── test_sort_then_unique ───────────────────────────────────────────────── */
static void test_sort_then_unique(void)
{
    /* Full deduplication via sort + unique */
    int arr[] = {3, 1, 2, 1, 2, 3};
    int tmp[6];
    algo_sort(arr, 6, sizeof(int), cmp_int, NULL, tmp);
    /* arr = {1, 1, 2, 2, 3, 3} */
    usize n = algo_unique(arr, 6, sizeof(int), cmp_int, NULL);
    EXPECT(n == 3);
    EXPECT(arr[0] == 1 && arr[1] == 2 && arr[2] == 3);

    /* All same after sort + unique */
    int arr2[] = {5, 5, 5, 5};
    algo_sort(arr2, 4, sizeof(int), cmp_int, NULL, tmp);
    n = algo_unique(arr2, 4, sizeof(int), cmp_int, NULL);
    EXPECT(n == 1);
    EXPECT(arr2[0] == 5);

    /* Already unique after sort */
    int arr3[] = {4, 2, 1, 3};
    algo_sort(arr3, 4, sizeof(int), cmp_int, NULL, tmp);
    n = algo_unique(arr3, 4, sizeof(int), cmp_int, NULL);
    EXPECT(n == 4);
    EXPECT(arr3[0] == 1 && arr3[1] == 2 && arr3[2] == 3 && arr3[3] == 4);
}

/* ── test_idempotency ────────────────────────────────────────────────────── */
static void test_idempotency(void)
{
    /* unique(unique(x)) == unique(x) — applying twice gives the same n */
    int arr[] = {1, 1, 2, 3, 3, 3, 4, 4, 5};
    int snap[9];
    memcpy(snap, arr, sizeof(arr));

    usize n1 = algo_unique(arr, 9, sizeof(int), cmp_int, NULL);

    /* Snapshot result */
    int after[9];
    memcpy(after, arr, sizeof(arr));

    /* Apply again on the valid prefix */
    usize n2 = algo_unique(arr, n1, sizeof(int), cmp_int, NULL);

    EXPECT(n1 == n2);
    for (usize i = 0; i < n1; i++) {
        EXPECT(arr[i] == after[i]);
    }
}

/* ── test_typed_macro ────────────────────────────────────────────────────── */
static void test_typed_macro(void)
{
    int arr[] = {1, 1, 2, 2, 3, 4, 4};
    usize n = ALGO_UNIQUE_TYPED(arr, 7, int, cmp_int, NULL);
    EXPECT(n == 4);
    EXPECT(arr[0] == 1 && arr[1] == 2 && arr[2] == 3 && arr[3] == 4);

    /* Empty via typed macro */
    n = ALGO_UNIQUE_TYPED(arr, 0, int, cmp_int, NULL);
    EXPECT(n == 0);
}

/* ── test_typed_slice ────────────────────────────────────────────────────── */
static void test_typed_slice(void)
{
    int buf[] = {10, 10, 20, 30, 30, 30, 40};
    slice_int sv = slice_int_from(buf, 7);

    usize n = algo_unique_slice_int(sv, cmp_int, NULL);
    EXPECT(n == 4);
    EXPECT(buf[0] == 10 && buf[1] == 20 && buf[2] == 30 && buf[3] == 40);

    /* Caller updates sv.len */
    sv.len = n;
    EXPECT(algo_unique_slice_int(sv, cmp_int, NULL) == 4); /* idempotent */

    /* Empty slice */
    slice_int empty = slice_int_empty();
    EXPECT(algo_unique_slice_int(empty, cmp_int, NULL) == 0);
}

/* ── test_context_parameter ──────────────────────────────────────────────── */
static void test_context_parameter(void)
{
    /* threshold=10: values within 10 of each other are considered "equal" */
    int arr[] = {1, 5, 8, 20, 21, 50};
    int threshold = 10;
    /* Pairs: (1,5)=near → collapse; (5,8) already collapsed to (1); 
     * (collapsed, 20)=far → keep; (20,21)=near → collapse; (21,50)=far → keep */
    /* Note: comparison is always prev (last written) vs curr */
    usize n = algo_unique(arr, 6, sizeof(int), cmp_int_near, &threshold);
    /* 1 stays; 5 is within 10 of 1 → skip; 8 is within 10 of 1 → skip;
     * 20 is far from 1 → keep; 21 is within 10 of 20 → skip;
     * 50 is far from 20 → keep */
    EXPECT(n == 3);
    EXPECT(arr[0] == 1 && arr[1] == 20 && arr[2] == 50);
}

/* ── test_point_struct ───────────────────────────────────────────────────── */
static void test_point_struct(void)
{
    /* Consecutive duplicates by key */
    Point arr[] = {
        {1, 10}, {1, 20},  /* duplicate key=1 */
        {2, 30},
        {3, 40}, {3, 50}, {3, 60}, /* run of key=3 */
        {4, 70},
    };
    slice_Point sv = slice_Point_from(arr, 7);

    usize n = algo_unique_slice_Point(sv, cmp_point_key, NULL);
    EXPECT(n == 4);
    EXPECT(arr[0].key == 1 && arr[1].key == 2 &&
           arr[2].key == 3 && arr[3].key == 4);
    /* First occurrence's val is preserved */
    EXPECT(arr[0].val == 10 && arr[2].val == 40);

    /* Empty Point slice */
    slice_Point empty = slice_Point_empty();
    EXPECT(algo_unique_slice_Point(empty, cmp_point_key, NULL) == 0);
}

/* ── Unit test entry point ───────────────────────────────────────────────── */
int main(void)
{
    (void)unique_slice_suppress_unused;

    test_empty();
    test_single_element();
    test_all_same();
    test_no_duplicates();
    test_basic_dedup();
    test_long_run();
    test_boundary_duplicates();
    test_consecutive_only();
    test_sort_then_unique();
    test_idempotency();
    test_typed_macro();
    test_typed_slice();
    test_context_parameter();
    test_point_struct();

    if (g_failed == 0) {
        printf("OK  unique_test  (all assertions passed)\n");
        return 0;
    }
    fprintf(stderr,
            "FAILED  unique_test  (%d assertion(s) failed)\n", g_failed);
    return 1;
}

#else /* CANON_FUZZING */

/* ════════════════════════════════════════════════════════════════════════════
   Fuzz entry point
   ════════════════════════════════════════════════════════════════════════════ */

static void unique_fuzz_suppress_unused(void)
{
    (void)algo_unique_slice_int;
    (void)algo_unique_slice_Point;
    (void)slice_int_from;
    (void)slice_int_empty;
    (void)slice_Point_from;
    (void)slice_Point_empty;
}

/*
 * Fuzz algo_unique on raw int input.
 *
 * Invariants:
 *   1. n in [1, len] for non-empty input (0 for empty)
 *   2. No consecutive equal pairs in arr[0..n-1]
 *   3. Idempotent: unique(unique(x)) returns same n
 *   4. n <= len (never grows)
 *   5. First element preserved: arr[0] unchanged after unique
 *   6. Sort-then-unique: n equals the count of distinct values
 */

static int fuzz_cmp_int(const void* a, const void* b, void* ctx)
{
    (void)ctx;
    int va = *(const int*)a;
    int vb = *(const int*)b;
    return (va > vb) - (va < vb);
}

/* Count distinct values in a sorted array */
static usize count_distinct(const int* arr, usize n)
{
    if (n == 0) return 0;
    usize count = 1;
    for (usize i = 1; i < n; i++) {
        if (arr[i] != arr[i-1]) count++;
    }
    return count;
}

#define UNIQUE_FUZZ_MAX 256

int LLVMFuzzerTestOneInput(const u8* data, usize size)
{
    (void)unique_fuzz_suppress_unused;
    (void)unique_slice_suppress_unused;

    if (size < sizeof(int)) return 0;

    usize n = size / sizeof(int);
    if (n > UNIQUE_FUZZ_MAX) n = UNIQUE_FUZZ_MAX;

    int arr[UNIQUE_FUZZ_MAX];
    int arr2[UNIQUE_FUZZ_MAX];
    int tmp[UNIQUE_FUZZ_MAX];
    memcpy(arr,  data, n * sizeof(int));
    memcpy(arr2, data, n * sizeof(int));

    int first = (n > 0) ? arr[0] : 0;

    /* Invariants 1, 2, 4 */
    usize u = algo_unique(arr, n, sizeof(int), fuzz_cmp_int, NULL);

    if (n == 0 && u != 0) __builtin_trap();
    if (n > 0 && (u == 0 || u > n)) __builtin_trap();

    /* Invariant 2: no consecutive equal pairs */
    for (usize i = 1; i < u; i++) {
        if (arr[i] == arr[i-1]) __builtin_trap();
    }

    /* Invariant 5: first element unchanged */
    if (n > 0 && arr[0] != first) __builtin_trap();

    /* Invariant 3: idempotent */
    usize u2 = algo_unique(arr, u, sizeof(int), fuzz_cmp_int, NULL);
    if (u2 != u) __builtin_trap();

    /* Invariant 6: sort-then-unique n equals distinct count */
    algo_sort(arr2, n, sizeof(int), fuzz_cmp_int, NULL, tmp);
    usize su = algo_unique(arr2, n, sizeof(int), fuzz_cmp_int, NULL);
    usize distinct = count_distinct(arr2, n); /* arr2 still sorted up to su */

    /* After unique on sorted array, arr2[0..su-1] is sorted and unique */
    if (su != count_distinct(arr2, su)) __builtin_trap();
    (void)distinct;

    return 0;
}

#endif /* CANON_FUZZING */
