/**
 * @file unique_mangle.h
 * @brief Name conventions for Canon-C unique slice variant
 *
 * Controls how the typed slice variant function generated by
 * DEFINE_ALGO_UNIQUE is named. Override the macro before including
 * unique.h to rename the generated function.
 *
 * The generic function (algo_unique) has a fixed name and is not
 * affected by this file.
 *
 * Override example:
 * ```c
 * #define ALGO_UNIQUE_SLICE_FN(type)  myns_unique_##type
 * #include "algo/unique/unique.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * unique_mangle.h has no includes of its own. It is included by
 * unique_impl.h, unique_decl.h, and unique.h before any logic.
 *
 * @sa unique_impl.h — uses this name in the generated symbol
 * @sa unique_decl.h — forward declaration using this name
 * @sa unique_defn.h — definition using this name
 */
#ifndef CANON_ALGO_UNIQUE_MANGLE_H
#define CANON_ALGO_UNIQUE_MANGLE_H

/**
 * @def ALGO_UNIQUE_SLICE_FN(type)
 * @brief Name of the typed unique slice function for a given element type
 *
 * Default: algo_unique_slice_##type  (e.g. algo_unique_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_UNIQUE_SLICE_FN(type)  myns_unique_##type
 * ```
 */
#ifndef ALGO_UNIQUE_SLICE_FN
    #define ALGO_UNIQUE_SLICE_FN(type) algo_unique_slice_##type
#endif

#endif /* CANON_ALGO_UNIQUE_MANGLE_H */
