/**
 * @file find_mangle.h
 * @brief Name conventions for Canon-C find slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_FIND are named. Override any macro before including
 * find.h to rename the generated functions.
 *
 * The generic function (algo_find) has a fixed name and is not
 * affected by this file.
 *
 * Override example:
 * ```c
 * #define ALGO_FIND_SLICE_FN(type)        myns_find_##type
 * #define ALGO_FIND_INDEX_SLICE_FN(type)  myns_find_index_##type
 * #include "algo/find/find.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * find_mangle.h has no includes of its own. It is included by
 * find_impl.h, find_decl.h, and find.h before any logic.
 *
 * @sa find_impl.h — uses these names in generated symbols
 * @sa find_decl.h — forward declarations using these names
 * @sa find_defn.h — definitions using these names
 */
#ifndef CANON_ALGO_FIND_MANGLE_H
#define CANON_ALGO_FIND_MANGLE_H

/**
 * @def ALGO_FIND_SLICE_FN(type)
 * @brief Name of the typed find-by-value slice function
 *
 * Default: algo_find_slice_##type  (e.g. algo_find_slice_int)
 * Returns option_##type — Some(value) on match, None if not found.
 */
#ifndef ALGO_FIND_SLICE_FN
    #define ALGO_FIND_SLICE_FN(type) algo_find_slice_##type
#endif

/**
 * @def ALGO_FIND_INDEX_SLICE_FN(type)
 * @brief Name of the typed find-by-index slice function
 *
 * Default: algo_find_index_slice_##type  (e.g. algo_find_index_slice_int)
 * Returns usize index — CANON_USIZE_MAX if not found.
 */
#ifndef ALGO_FIND_INDEX_SLICE_FN
    #define ALGO_FIND_INDEX_SLICE_FN(type) algo_find_index_slice_##type
#endif

#endif /* CANON_ALGO_FIND_MANGLE_H */
