/**
 * @file map_mangle.h
 * @brief Name conventions for Canon-C map slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_MAP are named. Override any macro before including
 * map.h to rename the generated functions.
 *
 * The generic functions (algo_map, algo_map_inplace) have fixed names
 * and are not affected by this file.
 *
 * Override example (rename slice variants to myns_map / myns_map_inplace):
 * ```c
 * #define ALGO_MAP_SLICE_FN(in_type, out_type)  myns_map_##in_type##_##out_type
 * #define ALGO_MAP_INPLACE_SLICE_FN(type)       myns_map_inplace_##type
 * #include "algo/map/map.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * map_mangle.h has no includes of its own. It is included by map_impl.h,
 * map_decl.h, and map.h before any logic.
 *
 * @sa map_impl.h  — uses these names in all generated symbols
 * @sa map_decl.h  — forward declarations using these names
 * @sa map_defn.h  — definitions using these names
 */
#ifndef CANON_ALGO_MAP_MANGLE_H
#define CANON_ALGO_MAP_MANGLE_H

/**
 * @def ALGO_MAP_SLICE_FN(in_type, out_type)
 * @brief Name of the typed cross-type map slice function
 *
 * Default: algo_map_slice_##in_type##_##out_type
 *          e.g. algo_map_slice_int_double
 *
 * Override to rename:
 * ```c
 * #define ALGO_MAP_SLICE_FN(in_type, out_type)  myns_map_##in_type##_##out_type
 * ```
 */
#ifndef ALGO_MAP_SLICE_FN
    #define ALGO_MAP_SLICE_FN(in_type, out_type) algo_map_slice_##in_type##_##out_type
#endif

/**
 * @def ALGO_MAP_INPLACE_SLICE_FN(type)
 * @brief Name of the typed in-place map slice function
 *
 * Default: algo_map_inplace_slice_##type
 *          e.g. algo_map_inplace_slice_int
 *
 * Override to rename:
 * ```c
 * #define ALGO_MAP_INPLACE_SLICE_FN(type)  myns_map_inplace_##type
 * ```
 */
#ifndef ALGO_MAP_INPLACE_SLICE_FN
    #define ALGO_MAP_INPLACE_SLICE_FN(type) algo_map_inplace_slice_##type
#endif

#endif /* CANON_ALGO_MAP_MANGLE_H */
