/**
 * @file sort_mangle.h
 * @brief Name conventions and tuning knobs for Canon-C sort slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_SORT are named, and sets the two size constants used
 * internally by the sort implementation. Override any macro before
 * including sort.h to rename the generated functions or adjust limits.
 *
 * The generic functions (algo_sort, algo_is_sorted) have fixed names
 * and are not affected by the slice name macros.
 *
 * Override example (rename slice variants):
 * ```c
 * #define ALGO_SORT_SLICE_FN(type)      myns_sort_##type
 * #define ALGO_IS_SORTED_SLICE_FN(type) myns_is_sorted_##type
 * #include "algo/sort/sort.h"
 * ```
 *
 * Override example (larger swap buffer for very large structs):
 * ```c
 * #define ALGO_SORT_SWAP_BUF_SIZE ((usize)1024)
 * #include "algo/sort/sort.h"
 * ```
 *
 * Override example (larger stack temp for ALGO_SORT_TYPED):
 * ```c
 * #define ALGO_SORT_STACK_TEMP_MAX 256
 * #include "algo/sort/sort.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * sort_mangle.h has no includes of its own. It is included by sort_impl.h,
 * sort_decl.h, and sort.h before any logic.
 *
 * @sa sort_impl.h — uses these constants and names
 * @sa sort_decl.h — forward declarations using these names
 * @sa sort_defn.h — definitions using these names
 */
#ifndef CANON_ALGO_SORT_MANGLE_H
#define CANON_ALGO_SORT_MANGLE_H

/**
 * @def ALGO_SORT_SWAP_BUF_SIZE
 * @brief Size in bytes of the fixed stack buffer used to swap two elements
 *
 * The internal swap helper uses a stack buffer of this size. Elements
 * that fit within it are swapped with three mem_copy calls. Elements
 * larger than this fall back to a byte-by-byte loop — correct but slower.
 * Default: 256 bytes — handles all primitive types, pointers, and most structs.
 *
 * Override before including sort.h if your element type exceeds 256 bytes:
 * ```c
 * #define ALGO_SORT_SWAP_BUF_SIZE ((usize)1024)
 * #include "algo/sort/sort.h"
 * ```
 */
#ifndef ALGO_SORT_SWAP_BUF_SIZE
    #define ALGO_SORT_SWAP_BUF_SIZE ((usize)256)
#endif

/**
 * @def ALGO_SORT_STACK_TEMP_MAX
 * @brief Maximum number of elements for which ALGO_SORT_TYPED allocates a
 *        stack temp buffer
 *
 * ALGO_SORT_TYPED allocates a stack array of Type[ALGO_SORT_STACK_TEMP_MAX]
 * to use as the merge sort scratch buffer. When len exceeds this value,
 * the macro passes NULL and falls back to O(n²) insertion sort. For large
 * arrays, call algo_sort() directly with a caller-managed heap or arena buffer.
 *
 * This is a compile-time constant — not a VLA.
 * Default: 128 elements.
 *
 * Override before including sort.h:
 * ```c
 * #define ALGO_SORT_STACK_TEMP_MAX 256
 * #include "algo/sort/sort.h"
 * ```
 */
#ifndef ALGO_SORT_STACK_TEMP_MAX
    #define ALGO_SORT_STACK_TEMP_MAX 128
#endif

/**
 * @def ALGO_SORT_SLICE_FN(type)
 * @brief Name of the typed in-place sort slice function
 *
 * Default: algo_sort_slice_##type  (e.g. algo_sort_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_SORT_SLICE_FN(type)  myns_sort_##type
 * ```
 */
#ifndef ALGO_SORT_SLICE_FN
    #define ALGO_SORT_SLICE_FN(type) algo_sort_slice_##type
#endif

/**
 * @def ALGO_IS_SORTED_SLICE_FN(type)
 * @brief Name of the typed sorted-check slice function
 *
 * Default: algo_is_sorted_slice_##type  (e.g. algo_is_sorted_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_IS_SORTED_SLICE_FN(type)  myns_is_sorted_##type
 * ```
 */
#ifndef ALGO_IS_SORTED_SLICE_FN
    #define ALGO_IS_SORTED_SLICE_FN(type) algo_is_sorted_slice_##type
#endif

#endif /* CANON_ALGO_SORT_MANGLE_H */
