/**
 * @file reverse_mangle.h
 * @brief Name conventions and tuning knobs for Canon-C reverse slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_REVERSE are named, and sets the swap buffer size used
 * by algo_reverse internally. Override any macro before including
 * reverse.h to rename the generated functions or adjust the buffer.
 *
 * The generic functions (algo_reverse, algo_is_palindrome) have fixed
 * names and are not affected by the slice name macros.
 *
 * Override example (rename slice variants to myns_reverse / myns_palindrome):
 * ```c
 * #define ALGO_REVERSE_SLICE_FN(type)       myns_reverse_##type
 * #define ALGO_IS_PALINDROME_SLICE_FN(type) myns_palindrome_##type
 * #include "algo/reverse/reverse.h"
 * ```
 *
 * Override example (larger swap buffer for very large structs):
 * ```c
 * #define ALGO_REVERSE_SWAP_BUF_SIZE ((usize)1024)
 * #include "algo/reverse/reverse.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * reverse_mangle.h has no includes of its own. It is included by
 * reverse_impl.h, reverse_decl.h, and reverse.h before any logic.
 *
 * @sa reverse_impl.h — uses these names and the buffer size constant
 * @sa reverse_decl.h — forward declarations using these names
 * @sa reverse_defn.h — definitions using these names
 */
#ifndef CANON_ALGO_REVERSE_MANGLE_H
#define CANON_ALGO_REVERSE_MANGLE_H

/**
 * @def ALGO_REVERSE_SWAP_BUF_SIZE
 * @brief Maximum element size (bytes) supported by algo_reverse
 *
 * algo_reverse uses a fixed-size stack buffer of this size when swapping
 * elements. Elements larger than this value trigger a contract failure.
 * Default: 256 bytes — handles all primitive types, pointers, and most structs.
 *
 * Override before including reverse.h if your element type exceeds 256 bytes:
 * ```c
 * #define ALGO_REVERSE_SWAP_BUF_SIZE ((usize)1024)
 * #include "algo/reverse/reverse.h"
 * ```
 */
#ifndef ALGO_REVERSE_SWAP_BUF_SIZE
    #define ALGO_REVERSE_SWAP_BUF_SIZE ((usize)256)
#endif

/**
 * @def ALGO_REVERSE_SLICE_FN(type)
 * @brief Name of the typed in-place reverse slice function
 *
 * Default: algo_reverse_slice_##type  (e.g. algo_reverse_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_REVERSE_SLICE_FN(type)  myns_reverse_##type
 * ```
 */
#ifndef ALGO_REVERSE_SLICE_FN
    #define ALGO_REVERSE_SLICE_FN(type) algo_reverse_slice_##type
#endif

/**
 * @def ALGO_IS_PALINDROME_SLICE_FN(type)
 * @brief Name of the typed palindrome-check slice function
 *
 * Default: algo_is_palindrome_slice_##type  (e.g. algo_is_palindrome_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_IS_PALINDROME_SLICE_FN(type)  myns_palindrome_##type
 * ```
 */
#ifndef ALGO_IS_PALINDROME_SLICE_FN
    #define ALGO_IS_PALINDROME_SLICE_FN(type) algo_is_palindrome_slice_##type
#endif

#endif /* CANON_ALGO_REVERSE_MANGLE_H */
