/***************************************************************************
 * Copyright (C) 2026 Eclipse Canon-C contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated.
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT AND CC0-1.0
 **************************************************************************/

/**
 * @file search_mangle.h
 * @brief Name conventions for Canon-C search slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_SEARCH are named. Override any macro before including
 * search.h to rename the generated functions.
 *
 * The generic functions (algo_lower_bound, algo_upper_bound,
 * algo_find_sorted, algo_binary_search, algo_equal_range) have fixed
 * names and are not affected by this file.
 *
 * Override example (rename slice variants to myns_lower / myns_upper / etc.):
 * ```c
 * #define ALGO_LOWER_BOUND_SLICE_FN(type)   myns_lower_##type
 * #define ALGO_UPPER_BOUND_SLICE_FN(type)   myns_upper_##type
 * #define ALGO_FIND_SORTED_SLICE_FN(type)   myns_find_##type
 * #define ALGO_BINARY_SEARCH_SLICE_FN(type) myns_search_##type
 * #define ALGO_EQUAL_RANGE_SLICE_FN(type)   myns_range_##type
 * #include "algo/search/search.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * search_mangle.h has no includes of its own. It is included by
 * search_impl.h, search_decl.h, and search.h before any logic.
 *
 * @sa search_impl.h — uses these names in all generated symbols
 * @sa search_decl.h — forward declarations using these names
 * @sa search_defn.h — definitions using these names
 */
#ifndef CANON_ALGO_SEARCH_MANGLE_H
#define CANON_ALGO_SEARCH_MANGLE_H

/**
 * @def ALGO_LOWER_BOUND_SLICE_FN(type)
 * @brief Name of the typed lower-bound slice function
 *
 * Default: algo_lower_bound_slice_##type  (e.g. algo_lower_bound_slice_int)
 */
#ifndef ALGO_LOWER_BOUND_SLICE_FN
    #define ALGO_LOWER_BOUND_SLICE_FN(type) algo_lower_bound_slice_##type
#endif

/**
 * @def ALGO_UPPER_BOUND_SLICE_FN(type)
 * @brief Name of the typed upper-bound slice function
 *
 * Default: algo_upper_bound_slice_##type  (e.g. algo_upper_bound_slice_int)
 */
#ifndef ALGO_UPPER_BOUND_SLICE_FN
    #define ALGO_UPPER_BOUND_SLICE_FN(type) algo_upper_bound_slice_##type
#endif

/**
 * @def ALGO_FIND_SORTED_SLICE_FN(type)
 * @brief Name of the typed exact-match lookup slice function
 *
 * Default: algo_find_sorted_slice_##type  (e.g. algo_find_sorted_slice_int)
 */
#ifndef ALGO_FIND_SORTED_SLICE_FN
    #define ALGO_FIND_SORTED_SLICE_FN(type) algo_find_sorted_slice_##type
#endif

/**
 * @def ALGO_BINARY_SEARCH_SLICE_FN(type)
 * @brief Name of the typed boolean existence-check slice function
 *
 * Default: algo_binary_search_slice_##type  (e.g. algo_binary_search_slice_int)
 */
#ifndef ALGO_BINARY_SEARCH_SLICE_FN
    #define ALGO_BINARY_SEARCH_SLICE_FN(type) algo_binary_search_slice_##type
#endif

/**
 * @def ALGO_EQUAL_RANGE_SLICE_FN(type)
 * @brief Name of the typed equal-range slice function
 *
 * Default: algo_equal_range_slice_##type  (e.g. algo_equal_range_slice_int)
 */
#ifndef ALGO_EQUAL_RANGE_SLICE_FN
    #define ALGO_EQUAL_RANGE_SLICE_FN(type) algo_equal_range_slice_##type
#endif

#endif /* CANON_ALGO_SEARCH_MANGLE_H */
