/***************************************************************************
 * Copyright (C) 2026 Eclipse Canon-C contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated.
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT AND CC0-1.0
 **************************************************************************/

/**
 * @file fold_mangle.h
 * @brief Name conventions for Canon-C fold slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_FOLD are named. Override any macro before including
 * fold.h to rename the generated functions.
 *
 * The macro-level interfaces (ALGO_FOLD, ALGO_FOLD_RESULT) are not
 * affected by this file — they are not name-parameterized.
 *
 * Override example:
 * ```c
 * #define ALGO_FOLD_SLICE_FN(type)         myns_fold_##type
 * #define ALGO_FOLD_RESULT_SLICE_FN(type)  myns_fold_result_##type
 * #include "algo/fold/fold.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * fold_mangle.h has no includes of its own. It is included by
 * fold_impl.h, fold_decl.h, and fold.h before any logic.
 *
 * @sa fold_impl.h — included by fold_defn.h
 * @sa fold_decl.h — forward declarations
 * @sa fold_defn.h — definitions for separate compilation
 */
#ifndef CANON_ALGO_FOLD_MANGLE_H
#define CANON_ALGO_FOLD_MANGLE_H

/**
 * @def ALGO_FOLD_SLICE_FN(type)
 * @brief Name of the typed infallible fold slice function
 *
 * Default: algo_fold_slice_##type  (e.g. algo_fold_slice_int)
 */
#ifndef ALGO_FOLD_SLICE_FN
    #define ALGO_FOLD_SLICE_FN(type) algo_fold_slice_##type
#endif

/**
 * @def ALGO_FOLD_RESULT_SLICE_FN(type)
 * @brief Name of the typed fallible fold slice function
 *
 * Default: algo_fold_result_slice_##type  (e.g. algo_fold_result_slice_int)
 */
#ifndef ALGO_FOLD_RESULT_SLICE_FN
    #define ALGO_FOLD_RESULT_SLICE_FN(type) algo_fold_result_slice_##type
#endif

#endif /* CANON_ALGO_FOLD_MANGLE_H */
