/***************************************************************************
 * Copyright (C) 2026 Eclipse Canon-C contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated.
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT AND CC0-1.0
 **************************************************************************/

#ifndef CANON_DATA_VEC_DECL_H
#define CANON_DATA_VEC_DECL_H

#include "data/vec/vec_mangle.h"
#include "data/vec/vec_impl.h"

/**
 * @file vec_decl.h
 * @brief Forward declarations for Canon-C typed vectors
 *
 * Use this file in headers to declare a typed vector type and its function
 * signatures without emitting any function definitions. Pair with vec_defn.h
 * in exactly one .c file to emit definitions.
 *
 * Core ideas:
 * ────────────────────────────────────────────────────────────────────────────
 * - Declares struct layout and all function signatures
 * - Emits zero function bodies — safe to include in multiple translation units
 * - Linkage is always `extern` here (forward declarations)
 * - Pair with DEFINE_VEC() in vec_defn.h for the matching definitions
 *
 * Portability:
 * ────────────────────────────────────────────────────────────────────────────
 * - Requires C99 or later
 *
 * Typical usage — in a shared header (e.g. tasks.h):
 * ```c
 * #include "data/vec/vec_decl.h"
 * DECLARE_VEC(int)
 * DECLARE_VEC(Task)
 * ```
 *
 * Matching definition — in exactly one .c file (e.g. tasks.c):
 * ```c
 * #include "data/vec/vec_defn.h"
 * DEFINE_VEC(static, int)
 * DEFINE_VEC(static, Task)
 * ```
 *
 * @sa vec_defn.h, vec_mangle.h, vec_impl.h, vec.h
 */

/* ════════════════════════════════════════════════════════════════════════════
   DECLARE_VEC — forward-declare a typed vector and all its functions
   ════════════════════════════════════════════════════════════════════════════ */

/**
 * @brief Declares a typed vector, iterator, slice, and all associated functions
 *
 * Emits:
 * - Struct typedefs: vec_##type, vec_##type##_iter, vec_##type##_slice
 * - extern declarations for every function generated by DEFINE_VEC()
 * - The per-instantiation lifetime helpers (static inline) are also emitted
 *   here; they have empty bodies in release builds and are header-only by
 *   nature (no extern declaration needed).
 *
 * @param type Element type (must be a valid C identifier — use typedef for pointers)
 *
 * Pointer types:
 * ```c
 * typedef const char* cstr;
 * DECLARE_VEC(cstr)
 * ```
 *
 * @note Must be matched by exactly one DEFINE_VEC(linkage, type) in a .c file.
 * @note Do NOT use DECLARE_VEC if you are using the header-only path via vec.h.
 *
 * Note on result__Bool_Error:
 *   push, pop, insert, remove, append_array, and extend return result__Bool_Error
 *   (not result_bool_Error) because CANON_RESULT(bool, Error) token-pastes to
 *   result__Bool_Error in C99 — bool expands to _Bool before ## sees it.
 *   These extern signatures must match the definitions emitted by DEFINE_VEC exactly.
 */
/* cppcheck-suppress misra-c2012-20.7 ; MISRA-DEV-012 */
#define DECLARE_VEC(type) \
\
IMPL_VEC_STRUCTS( \
    MANGLE_VEC_TYPE(type), \
    MANGLE_VEC_STRUCT_TAG(type), \
    MANGLE_VEC_ITER_TYPE(type), \
    MANGLE_VEC_ITER_STRUCT_TAG(type), \
    MANGLE_VEC_SLICE_TYPE(type), \
    MANGLE_VEC_SLICE_STRUCT_TAG(type), \
    MANGLE_VEC_LIFETIME_OPEN(type), \
    MANGLE_VEC_LIFETIME_CLOSE(type), \
    type \
) \
\
/* Constructors / destructor */ \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_INIT(type)(borrowed(type*) buffer, usize capacity); \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_EMPTY(type)(void); \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_ALLOC(type)(usize capacity); \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_ARENA_ALLOC(type)(borrowed(Arena*) arena, usize capacity); \
extern void                  MANGLE_VEC_FREE(type)(dropped(MANGLE_VEC_TYPE(type)*) v); \
\
/* Queries */ \
extern usize MANGLE_VEC_LEN(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
extern usize MANGLE_VEC_CAPACITY(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
extern usize MANGLE_VEC_REMAINING(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
extern bool  MANGLE_VEC_IS_EMPTY(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
extern bool  MANGLE_VEC_IS_FULL(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
\
/* Element access */ \
extern bool                         MANGLE_VEC_GET(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v, usize i, borrowed((type)*) out); \
extern MANGLE_VEC_OPTION_TYPE(type) MANGLE_VEC_GET_OPTION(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v, usize i); \
extern type                         MANGLE_VEC_GET_UNCHECKED(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v, usize i); \
extern borrowed((type)*)              MANGLE_VEC_AT(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v, usize i); \
extern bool                         MANGLE_VEC_SET(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, usize i, type val); \
extern borrowed((type)*)              MANGLE_VEC_FIRST(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
extern borrowed((type)*)              MANGLE_VEC_LAST(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
extern borrowed((type)*)              MANGLE_VEC_DATA(type)(borrowed(const MANGLE_VEC_TYPE(type)*) v); \
\
/* Modification */ \
extern result__Bool_Error           MANGLE_VEC_PUSH(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, type item); \
extern bool                         MANGLE_VEC_TRY_PUSH(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, type item); \
extern void                         MANGLE_VEC_PUSH_UNCHECKED(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, type item); \
extern result__Bool_Error           MANGLE_VEC_POP(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, borrowed((type)*) out); \
extern MANGLE_VEC_OPTION_TYPE(type) MANGLE_VEC_POP_OPTION(type)(borrowed(MANGLE_VEC_TYPE(type)*) v); \
extern void                         MANGLE_VEC_CLEAR(type)(borrowed(MANGLE_VEC_TYPE(type)*) v); \
extern result__Bool_Error           MANGLE_VEC_INSERT(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, usize i, type item); \
extern result__Bool_Error           MANGLE_VEC_REMOVE(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, usize i, borrowed((type)*) out); \
extern MANGLE_VEC_OPTION_TYPE(type) MANGLE_VEC_REMOVE_OPTION(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, usize i); \
\
/* Bulk operations */ \
extern result__Bool_Error MANGLE_VEC_APPEND_ARRAY(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, borrowed(const type*) src, usize count); \
extern result__Bool_Error MANGLE_VEC_EXTEND(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, borrowed(const type*) src, usize count); \
extern void               MANGLE_VEC_FILL(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, type value, usize count); \
extern void               MANGLE_VEC_SWAP(type)(borrowed(MANGLE_VEC_TYPE(type)*) a, borrowed(MANGLE_VEC_TYPE(type)*) b); \
\
/* Iterator */ \
extern MANGLE_VEC_ITER_TYPE(type) MANGLE_VEC_ITER_INIT(type)(borrowed(MANGLE_VEC_TYPE(type)*) v); \
extern bool                       MANGLE_VEC_ITER_NEXT(type)(borrowed(MANGLE_VEC_ITER_TYPE(type)*) it, borrowed((type)*) out); \
\
/* Slice */ \
extern MANGLE_VEC_SLICE_TYPE(type)  MANGLE_VEC_SLICE_INIT(type)(borrowed(MANGLE_VEC_TYPE(type)*) v, usize start, usize end); \
extern borrowed((type)*)              MANGLE_VEC_SLICE_GET(type)(borrowed(const MANGLE_VEC_SLICE_TYPE(type)*) s, usize i);

#endif /* CANON_DATA_VEC_DECL_H */
