#ifndef CANON_DATA_VEC_DECL_H
#define CANON_DATA_VEC_DECL_H

#include "data/vec/vec_mangle.h"
#include "data/vec/vec_impl.h"

/**
 * @file vec_decl.h
 * @brief Forward declarations for Canon-C typed vectors
 *
 * Use this file in headers to declare a typed vector type and its function
 * signatures without emitting any function definitions. Pair with vec_defn.h
 * in exactly one .c file to emit definitions.
 *
 * Core ideas:
 * ────────────────────────────────────────────────────────────────────────────
 * - Declares struct layout and all function signatures
 * - Emits zero function bodies — safe to include in multiple translation units
 * - Linkage is always `extern` here (forward declarations)
 * - Pair with DEFINE_VEC() in vec_defn.h for the matching definitions
 *
 * Portability:
 * ────────────────────────────────────────────────────────────────────────────
 * - Requires C99 or later
 *
 * Typical usage — in a shared header (e.g. tasks.h):
 * ```c
 * #include "data/vec/vec_decl.h"
 * DECLARE_VEC(int)
 * DECLARE_VEC(Task)
 * ```
 *
 * Matching definition — in exactly one .c file (e.g. tasks.c):
 * ```c
 * #include "data/vec/vec_defn.h"
 * DEFINE_VEC(static, int)
 * DEFINE_VEC(static, Task)
 * ```
 *
 * @sa vec_defn.h, vec_mangle.h, vec_impl.h, vec.h
 */

/* ════════════════════════════════════════════════════════════════════════════
   DECLARE_VEC — forward-declare a typed vector and all its functions
   ════════════════════════════════════════════════════════════════════════════ */

/**
 * @brief Declares a typed vector, iterator, slice, and all associated functions
 *
 * Emits:
 * - Struct typedefs: canon_vec_##type, canon_vec_##type##_iter, canon_vec_##type##_slice
 * - extern declarations for every function generated by DEFINE_VEC()
 *
 * @param type Element type (must be a valid C identifier — use typedef for pointers)
 *
 * Pointer types:
 * ```c
 * typedef const char* cstr;
 * DECLARE_VEC(cstr)
 * ```
 *
 * @note Must be matched by exactly one DEFINE_VEC(linkage, type) in a .c file.
 * @note Do NOT use DECLARE_VEC if you are using the header-only path via vec.h.
 */
#define DECLARE_VEC(type) \
\
IMPL_VEC_STRUCTS( \
    MANGLE_VEC_TYPE(type), \
    MANGLE_VEC_STRUCT_TAG(type), \
    MANGLE_VEC_ITER_TYPE(type), \
    MANGLE_VEC_ITER_STRUCT_TAG(type), \
    MANGLE_VEC_SLICE_TYPE(type), \
    MANGLE_VEC_SLICE_STRUCT_TAG(type), \
    type \
) \
\
/* Constructors / destructor */ \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_INIT(type)(type* buffer, usize capacity); \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_EMPTY(type)(void); \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_ALLOC(type)(usize capacity); \
extern MANGLE_VEC_TYPE(type) MANGLE_VEC_ARENA_ALLOC(type)(Arena* arena, usize capacity); \
extern void                  MANGLE_VEC_FREE(type)(MANGLE_VEC_TYPE(type)* v); \
\
/* Queries */ \
extern usize MANGLE_VEC_LEN(type)(const MANGLE_VEC_TYPE(type)* v); \
extern usize MANGLE_VEC_CAPACITY(type)(const MANGLE_VEC_TYPE(type)* v); \
extern usize MANGLE_VEC_REMAINING(type)(const MANGLE_VEC_TYPE(type)* v); \
extern bool  MANGLE_VEC_IS_EMPTY(type)(const MANGLE_VEC_TYPE(type)* v); \
extern bool  MANGLE_VEC_IS_FULL(type)(const MANGLE_VEC_TYPE(type)* v); \
\
/* Element access */ \
extern bool                         MANGLE_VEC_GET(type)(const MANGLE_VEC_TYPE(type)* v, usize i, type* out); \
extern MANGLE_VEC_OPTION_TYPE(type) MANGLE_VEC_GET_OPTION(type)(const MANGLE_VEC_TYPE(type)* v, usize i); \
extern type                         MANGLE_VEC_GET_UNCHECKED(type)(const MANGLE_VEC_TYPE(type)* v, usize i); \
extern type*                        MANGLE_VEC_AT(type)(const MANGLE_VEC_TYPE(type)* v, usize i); \
extern bool                         MANGLE_VEC_SET(type)(MANGLE_VEC_TYPE(type)* v, usize i, type val); \
extern type*                        MANGLE_VEC_FIRST(type)(const MANGLE_VEC_TYPE(type)* v); \
extern type*                        MANGLE_VEC_LAST(type)(const MANGLE_VEC_TYPE(type)* v); \
extern type*                        MANGLE_VEC_DATA(type)(const MANGLE_VEC_TYPE(type)* v); \
\
/* Modification */ \
extern result_bool_Error            MANGLE_VEC_PUSH(type)(MANGLE_VEC_TYPE(type)* v, type item); \
extern bool                         MANGLE_VEC_TRY_PUSH(type)(MANGLE_VEC_TYPE(type)* v, type item); \
extern void                         MANGLE_VEC_PUSH_UNCHECKED(type)(MANGLE_VEC_TYPE(type)* v, type item); \
extern result_bool_Error            MANGLE_VEC_POP(type)(MANGLE_VEC_TYPE(type)* v, type* out); \
extern MANGLE_VEC_OPTION_TYPE(type) MANGLE_VEC_POP_OPTION(type)(MANGLE_VEC_TYPE(type)* v); \
extern void                         MANGLE_VEC_CLEAR(type)(MANGLE_VEC_TYPE(type)* v); \
extern result_bool_Error            MANGLE_VEC_INSERT(type)(MANGLE_VEC_TYPE(type)* v, usize i, type item); \
extern result_bool_Error            MANGLE_VEC_REMOVE(type)(MANGLE_VEC_TYPE(type)* v, usize i, type* out); \
extern MANGLE_VEC_OPTION_TYPE(type) MANGLE_VEC_REMOVE_OPTION(type)(MANGLE_VEC_TYPE(type)* v, usize i); \
\
/* Bulk operations */ \
extern result_bool_Error MANGLE_VEC_APPEND_ARRAY(type)(MANGLE_VEC_TYPE(type)* v, const type* src, usize count); \
extern result_bool_Error MANGLE_VEC_EXTEND(type)(MANGLE_VEC_TYPE(type)* v, const type* src, usize count); \
extern void              MANGLE_VEC_FILL(type)(MANGLE_VEC_TYPE(type)* v, type value, usize count); \
extern void              MANGLE_VEC_SWAP(type)(MANGLE_VEC_TYPE(type)* a, MANGLE_VEC_TYPE(type)* b); \
\
/* Iterator */ \
extern MANGLE_VEC_ITER_TYPE(type) MANGLE_VEC_ITER_INIT(type)(MANGLE_VEC_TYPE(type)* v); \
extern bool                       MANGLE_VEC_ITER_NEXT(type)(MANGLE_VEC_ITER_TYPE(type)* it, type* out); \
\
/* Slice */ \
extern MANGLE_VEC_SLICE_TYPE(type) MANGLE_VEC_SLICE_INIT(type)(MANGLE_VEC_TYPE(type)* v, usize start, usize end); \
extern type*                       MANGLE_VEC_SLICE_GET(type)(const MANGLE_VEC_SLICE_TYPE(type)* s, usize i);

#endif /* CANON_DATA_VEC_DECL_H */
