#ifndef CANON_DATA_DEQUE_DECL_H
#define CANON_DATA_DEQUE_DECL_H

#include "data/deque/deque_mangle.h"
#include "data/deque/deque_impl.h"

/**
 * @file deque_decl.h
 * @brief Forward declarations for Canon-C typed deques
 *
 * Use this file in headers to declare a typed deque type and its function
 * signatures without emitting any function definitions. Pair with deque_defn.h
 * in exactly one .c file to emit definitions.
 *
 * Core ideas:
 * ────────────────────────────────────────────────────────────────────────────
 * - Declares struct layout and all function signatures
 * - Emits zero function bodies — safe to include in multiple translation units
 * - Linkage is always `extern` here (forward declarations)
 * - Pair with DEFINE_DEQUE() in deque_defn.h for the matching definitions
 *
 * Portability:
 * ────────────────────────────────────────────────────────────────────────────
 * - Requires C99 or later
 *
 * Typical usage — in a shared header (e.g. tasks.h):
 * ```c
 * #include "data/deque/deque_decl.h"
 * DECLARE_DEQUE(int)
 * DECLARE_DEQUE(Task)
 * ```
 *
 * Matching definition — in exactly one .c file (e.g. tasks.c):
 * ```c
 * #include "data/deque/deque_defn.h"
 * CANON_OPTION(int)
 * DEFINE_DEQUE(, int)
 * CANON_OPTION(Task)
 * DEFINE_DEQUE(, Task)
 * ```
 *
 * @sa deque_defn.h, deque_mangle.h, deque_impl.h, deque.h
 */

/* ════════════════════════════════════════════════════════════════════════════
   DECLARE_DEQUE — forward-declare a typed deque and all its functions
   ════════════════════════════════════════════════════════════════════════════ */

/**
 * @brief Declares a typed deque struct and all associated function signatures
 *
 * Emits:
 * - Struct typedef: canon_deque_##type
 * - extern declarations for every function generated by DEFINE_DEQUE()
 *
 * @param type Element type (must be a valid C identifier — use typedef for pointers)
 *
 * Pointer types:
 * ```c
 * typedef const char* cstr;
 * DECLARE_DEQUE(cstr)
 * ```
 *
 * @note Must be matched by exactly one DEFINE_DEQUE(linkage, type) in a .c file.
 * @note Do NOT use DECLARE_DEQUE if you are using the header-only path via deque.h.
 * @note MANGLE_DEQUE_OPTION_TYPE(type) must be available at the declaration site —
 *       include semantics/option/option.h and call CANON_OPTION(type) beforehand.
 */
#define DECLARE_DEQUE(type) \
\
IMPL_DEQUE_STRUCT( \
    MANGLE_DEQUE_TYPE(type), \
    MANGLE_DEQUE_STRUCT_TAG(type), \
    type \
) \
\
/* Constructor */ \
extern void                  MANGLE_DEQUE_INIT(type)(MANGLE_DEQUE_TYPE(type)* d, type* buffer, usize capacity); \
extern MANGLE_DEQUE_TYPE(type) MANGLE_DEQUE_EMPTY(type)(void); \
\
/* Queries */ \
extern usize MANGLE_DEQUE_LEN(type)(const MANGLE_DEQUE_TYPE(type)* d); \
extern usize MANGLE_DEQUE_CAPACITY(type)(const MANGLE_DEQUE_TYPE(type)* d); \
extern usize MANGLE_DEQUE_REMAINING(type)(const MANGLE_DEQUE_TYPE(type)* d); \
extern bool  MANGLE_DEQUE_IS_EMPTY(type)(const MANGLE_DEQUE_TYPE(type)* d); \
extern bool  MANGLE_DEQUE_IS_FULL(type)(const MANGLE_DEQUE_TYPE(type)* d); \
\
/* Push */ \
extern result_bool_Error MANGLE_DEQUE_PUSH_FRONT(type)(MANGLE_DEQUE_TYPE(type)* d, type item); \
extern result_bool_Error MANGLE_DEQUE_PUSH_BACK(type)(MANGLE_DEQUE_TYPE(type)* d, type item); \
\
/* Pop — Result variants */ \
extern result_bool_Error MANGLE_DEQUE_POP_FRONT(type)(MANGLE_DEQUE_TYPE(type)* d, type* out); \
extern result_bool_Error MANGLE_DEQUE_POP_BACK(type)(MANGLE_DEQUE_TYPE(type)* d, type* out); \
\
/* Pop — Option variants */ \
extern MANGLE_DEQUE_OPTION_TYPE(type) MANGLE_DEQUE_POP_FRONT_OPTION(type)(MANGLE_DEQUE_TYPE(type)* d); \
extern MANGLE_DEQUE_OPTION_TYPE(type) MANGLE_DEQUE_POP_BACK_OPTION(type)(MANGLE_DEQUE_TYPE(type)* d); \
\
/* Peek — bool variants */ \
extern bool MANGLE_DEQUE_PEEK_FRONT(type)(const MANGLE_DEQUE_TYPE(type)* d, type* out); \
extern bool MANGLE_DEQUE_PEEK_BACK(type)(const MANGLE_DEQUE_TYPE(type)* d, type* out); \
\
/* Peek — Option variants */ \
extern MANGLE_DEQUE_OPTION_TYPE(type) MANGLE_DEQUE_PEEK_FRONT_OPTION(type)(const MANGLE_DEQUE_TYPE(type)* d); \
extern MANGLE_DEQUE_OPTION_TYPE(type) MANGLE_DEQUE_PEEK_BACK_OPTION(type)(const MANGLE_DEQUE_TYPE(type)* d); \
\
/* Misc */ \
extern void MANGLE_DEQUE_CLEAR(type)(MANGLE_DEQUE_TYPE(type)* d); \
extern void MANGLE_DEQUE_SWAP(type)(MANGLE_DEQUE_TYPE(type)* a, MANGLE_DEQUE_TYPE(type)* b);

#endif /* CANON_DATA_DEQUE_DECL_H */
