/**
 * @file filter_mangle.h
 * @brief Name conventions for Canon-C filter slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_FILTER are named. Override any macro before including
 * filter.h to rename the generated functions.
 *
 * The generic function (algo_filter) has a fixed name and is not
 * affected by this file.
 *
 * Override example (rename slice variant to myns_filter_int):
 * ```c
 * #define ALGO_FILTER_SLICE_FN(type)  myns_filter_##type
 * #include "algo/filter/filter.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * filter_mangle.h has no includes of its own. It is included by
 * filter_impl.h, filter_decl.h, and filter.h before any logic.
 *
 * @sa filter_impl.h — uses these names in all generated symbols
 * @sa filter_decl.h — forward declarations using these names
 * @sa filter_defn.h — definitions using these names
 */
#ifndef CANON_ALGO_FILTER_MANGLE_H
#define CANON_ALGO_FILTER_MANGLE_H

/**
 * @def ALGO_FILTER_SLICE_FN(type)
 * @brief Name of the typed filter slice function for a given element type
 *
 * Default: algo_filter_slice_##type  (e.g. algo_filter_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_FILTER_SLICE_FN(type) myns_filter_##type
 * ```
 */
#ifndef ALGO_FILTER_SLICE_FN
    #define ALGO_FILTER_SLICE_FN(type) algo_filter_slice_##type
#endif

#endif /* CANON_ALGO_FILTER_MANGLE_H */
