/***************************************************************************
 * Copyright (C) 2026 Eclipse Canon-C contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated.
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT AND CC0-1.0
 **************************************************************************/

/**
 * @file any_all_mangle.h
 * @brief Name conventions for Canon-C any_all slice variants
 *
 * Controls how the typed slice variant functions generated by
 * DEFINE_ALGO_ANY_ALL are named. Override any macro before including
 * any_all.h to rename the generated functions.
 *
 * The generic functions (algo_any, algo_all) have fixed names and
 * are not affected by this file.
 *
 * Override example (rename slice variants to myns_any / myns_all):
 * ```c
 * #define ALGO_ANY_SLICE_FN(type)  myns_any_##type
 * #define ALGO_ALL_SLICE_FN(type)  myns_all_##type
 * #include "algo/any_all/any_all.h"
 * ```
 *
 * Dependency rule:
 * ────────────────────────────────────────────────────────────────────────────
 * any_all_mangle.h has no includes of its own. It is included by
 * any_all_impl.h, any_all_decl.h, and any_all.h before any logic.
 *
 * @sa any_all_impl.h  — uses these names in all generated symbols
 * @sa any_all_decl.h  — forward declarations using these names
 * @sa any_all_defn.h  — definitions using these names
 */
#ifndef CANON_ALGO_ANY_ALL_MANGLE_H
#define CANON_ALGO_ANY_ALL_MANGLE_H

/**
 * @def ALGO_ANY_SLICE_FN(type)
 * @brief Name of the typed any-check slice function for a given element type
 *
 * Default: algo_any_slice_##type  (e.g. algo_any_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_ANY_SLICE_FN(type) myns_any_##type
 * ```
 */
#ifndef ALGO_ANY_SLICE_FN
    #define ALGO_ANY_SLICE_FN(type) algo_any_slice_##type
#endif

/**
 * @def ALGO_ALL_SLICE_FN(type)
 * @brief Name of the typed all-check slice function for a given element type
 *
 * Default: algo_all_slice_##type  (e.g. algo_all_slice_int)
 *
 * Override to rename:
 * ```c
 * #define ALGO_ALL_SLICE_FN(type) myns_all_##type
 * ```
 */
#ifndef ALGO_ALL_SLICE_FN
    #define ALGO_ALL_SLICE_FN(type) algo_all_slice_##type
#endif

#endif /* CANON_ALGO_ANY_ALL_MANGLE_H */
